### ISSUE TITLE
Groupe de services : architecture multipoller

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3203]
---

Author Name: **GIBERT Florian** (GIBERT Florian)
Original Redmine Issue: 5755, https://forge.centreon.com/issues/5755
Original Date: 2014-08-21

---

Si des groupes de services sont définis au niveau de la supervision mais n'ont pas de services associé au niveau du poller, le debug présente des warning : 

Warning Specified service group 'APP_CENTREON' has no members

**Comment by julienmathis** [comment]
Matthieu, 

What is the status of this issue ?

Thanks in advance.

**Comment by ganoze** [comment]
The best way to solve this case would be to *not* generate groups on pollers which have no members.

Would it be possible to implement this change in Centreon if it has not already be done ?

**Comment by julienmathis** [comment]
Do you think that the warning is not useless ? Is it realy a problem that a SG is empty ? 

If the UI manage this problem, we may encounter performance problem during the config files generation system...

**Comment by ganoze** [comment]
From Centreon Engine point of view whereas this is not a blocking problem, there's at least something strange in declaring a group and not using it. That's why there's a warning to point user's attention on this setting to ensure that this is really what he wants.

We could of course remove this warning from Centreon Engine because of performance issues on the UI side but that's not the cleaniest way to do it. Are you sure that this would be a bottleneck ?

**Comment by julienmathis** [comment]
Yes we can remove the warning !

**Comment by ganoze** [comment]
Committed in 1.4 branch of Centreon Engine.
