### ISSUE TITLE
Legacy ndo/ndolight patch

### ISSUE THREAD

**Issue by Leryan** [centreon/centreon#3794]
Hi,

I can't find the old ndolight patch for ndo 1.4b9. Is it possible to get this patch somewhere?

Thanks

**Comment by Sims24** [comment]
Hi, 

No longer available, anyway if you use this value for your data processing options, then the result will be the same : 

data_processing_options= 4325137

But my first advise would be to take a look at centreon-broker (https://github.com/centreon/centreon-broker) because of ndoutils-centreon end-of-life https://github.com/centreon/centreon/issues/3787 within the next major release. 

Thanks

**Comment by Leryan** [comment]
I already use centreon-broker, but for some reasons, we have production environment that cannot be changed.

But thanks for this option ;-)
