### ISSUE TITLE
[2.6.5] CSRF error appears in user massive change form

### ISSUE THREAD

**Issue by qdelance** [centreon/centreon#3852]
Go to Config => Users
Select many users
Select massive change
Red error related to CSRF (see screenshot)
![csrf](https://cloud.githubusercontent.com/assets/2544611/10689683/6194f1da-797d-11e5-8f03-efb8f4327067.png)

**Comment by qdelance** [comment]
It seems that this message does not block the action.
Good news is that the priority of this ticket is important.
However, I have a doubt the CSRF protection is real, it should be tested.

**Comment by mathieuchateau** [comment]
Hello,
I can generate this error message also in hostgroup. 
From my tests, it happens if I open items to new tabs (like to open let's say 5 items in different tabs).

How to reproduce:
open a host group, or whatever item. edit name,save. ok
open 2 host groups, or whaever items, then go to first one (not the last opened) and do same change. Issue happens.
