### ISSUE TITLE
[2.7.0-RC2] cbd ins't automaticlly started

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#3974]
Hi,
after a fresh install from 3.3 iso, cbd is not started after the first configuration genaration.

thanks
David

**Comment by julienmathis** [comment]
@ganoze do you think you can deliver a cbd with a empty configuration but who give possibility to have cbd launched :)

**Comment by ganoze** [comment]
I am not so fan of this idea. IMHO it would be better to implement a change in Centreon. Instead of just issuing a **/etc/init.d/cbd reload** after configuration generation it would be better to check status first with **/etc/init.d/cbd status** and according to return code either reload or restart.

**Comment by Sims24** [comment]
Hi guys, 

Not sure it's a good idea anyway, since the dawn of time in Centreon after a fresh install, we always had to start manually broker after pushing initial configuration. We need to do it one and only one time.

IMHO, if Centreon handle this part, this will probably add some complexity/specificities for highly available setup as we have only cbd rrd running and sometimes a custom master.run.

++

**Comment by ganoze** [comment]
@Sims24 there won't be any issue with HA setups because if you're asking in the web UI to reload the configuration then it will reload/restart on the current master (not on the slave) which is where the two cbd processes should be running in the first place.

IMHO allowing Centreon to restart cbd will be a huge gain for newcomers.

**Comment by Sims24** [comment]
@ganoze you're right for HA setups -_- ... "huge gain for newcomers" if you say so but it works like that for a while and IMHO, not a revolution ;)

**Comment by Sims24** [comment]
Moreover, I can sometime stop broker manually to have some (wanted) failover and I can't be sure that an other user or clapi script will not export the config and then trigger a broker restart ... 

It's about add a piece of code that will match 1..1 case for improvement but also accidentally impact some other things 1..n times. 

IMHO, still think it is a bad idea

**Comment by julienmathis** [comment]
So ? To resume ? 

Ok for implementing the possibility to restart broker even if the cbd is not started ?

@Sims24 @ganoze @golgoth31 ?

Personnaly : I think it can be usefull to test if the process is launch or not and select the right command : start or reload.

**Comment by ganoze** [comment]
IMHO, allowing Centreon to restart cbd is just common sense. I would like to see this feature implemented in Centreon.

**Comment by Sims24** [comment]
I'm not the one who will code this on so ...  :) if @ganoze think is a must have and brings benefits to a great number of users, then let's say ok ;)  Anyway at first sight doesn't sound essential to me or a top priority that's all ;) 
 
Thanks guys

**Comment by golgoth31** [comment]
Hello,
I think this feature is a must have as cbd is part of centreon and so, must also be fully driven by centreon-web. But, this 'cbd restart' can be linked to the state of broker in db: centreon-web is able to see if cbd is running or not (as shown in poller view), so, centreon-web should be able to decide if cbd have be (re)started or not. Of course this mechanism must be fully secured (just like the centengine one must be) and a cbd start failure must be presented into centreon-web .

**Comment by julienmathis** [comment]
Done for 2.7.3
