### ISSUE TITLE
[2.7.0] Users configuration show reverse enabled / disabled symbol

### ISSUE THREAD

**Issue by albundy83** [centreon/centreon#4055]
Hello,

first happy new year and continue like this !!!
Then, an issue ;)
In section Configuration  >  Users  >  Contacts / Users, the symbol shown when a user is disabled is a check mark and a forbidden sign when user is enabled... 
Maybe it could be the reverse ? or maybe I did not understand the purpose of this sign...
And also, no column name is displayed for this one : 
![nothing](https://cloud.githubusercontent.com/assets/1215213/12088965/332e9ff2-b2e0-11e5-8280-0cd30637380d.png)

Thanks a lot.

**Comment by querwin** [comment]
Hello,

The sign is forbiden when an user is activated because you can desactivate it while clicking on the symbol. This is the same thing for the activation of the user.

The second problem have been fixed by this commit : https://github.com/centreon/centreon/commit/838dab677258c421655e35c5d169d972c1c86a35

Regards,
