### ISSUE TITLE
Schedule immediate and forced check > Why not simplify to only one possibility ?

### ISSUE THREAD

**Issue by Moujimouja** [centreon/centreon#4176]
From a user point of view, when I want to refresh the perfdata / status of a service, I just want to be able to manually schedule a new check on a service and I want it to be executed asap.

So from my point of view, I suggest to delete the 2 possibilities for service manual scheduling to keep only one possibilit  that will do the equivalent of the "forced" one.

++

**Comment by matthieu-robin** [comment]
I'm agree with that, but you can remove this access with ACL and let only one.

**Comment by julienmathis** [comment]
The difference between the to is that if the service is passif, so he is not scheduled if the command is not forced. So there are a real difference between the two commands... 

so ... are you still convinced by your ask ?

**Comment by cmeschin** [comment]
Hi,
I think that both options have to stay because there is another important difference.
The forced check executes the command without verification of the timeperiod and risk to generate false events.
The normal check re-executes immediately the command if we are situated in the timeperiod otherwise timeperiod reschedule for the next good one.

And, as Matthieu said, you can deactivate the one or other one of the commands with ACL's.

cordially,

**Comment by julienmathis** [comment]
so let's keep the two possibilities :)
