### ISSUE TITLE
Additive inheritance doesn't work very well

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#4195]
Hello,

I have a problem with additive inheritance, when I use this parameter on host templates with parent, it doesn't work.

Please take a look on this picture:
![additive_inheritance](https://cloud.githubusercontent.com/assets/11076322/13143810/b8f0ccbc-d646-11e5-904e-7df3a36fa086.jpg)

For information, "Additive Inheritance" is enabled on each host template.

On the green schema, it works very well because Template1 hasn't a parent, so "additive inheritance" takes contacts on its "brother" (Template2).

On the red schema, it's doesn't work because the first template is Template2. This template has a parent so "additive inheritance" doesn't take contacts on its "brother" (Template1).

regards,

**Comment by julienmathis** [comment]
hé @ganoze ! can you investigate this problem ?

**Comment by cissoux** [comment]
Hello,

I also have a problem with additive inheritance with multiples templates.
It works well when i have 2 templates (like your first diagram) but don't work with 3 (and more) templates.
Additive Inheritance is enabled on each host template and templates don't have parent.

![sanstitre](https://cloud.githubusercontent.com/assets/22084314/18364995/0d8936f0-7611-11e6-9ef6-a9b794b02e8b.jpg)

You have the same problem ?
There are limitations on the number of contacts with Additive Inheritance ?

thank you for your help.

cis

**Comment by ganoze** [comment]
@s-duret @cissoux 

I finally found out what the issue was. There was both a misunderstanding and a bug. The additive inheritance feature is not expected to append all template contacts within the base host but instead to append the host's contacts to the first template with contacts (and this works recursively).

It's an interesting feature though, hence the Kind/Enhancement label. What do you think about it @julienmathis @lpinsivy ?

 So, in all your cases, only the contact of the first host template should have been notified. This is a bug from Centreon Engine that only occurs if the base host does not have contacts. Therefore I opened a ticket here centreon/centreon-engine#60

**Comment by lpinsivy** [comment]
Additive inheritance has been rewritten. Should be OK
