### ISSUE TITLE
Hostgroup filter not show all hostgroup

### ISSUE THREAD

**Issue by GhilesKDH** [centreon/centreon#4335]
Hello, 
In centreon 2.6.6, in monitoring menu i don't see all  hostgroup in the hostgroup filter.

any help ?
Thank you

**Comment by florian-asche** [comment]
Hi, the menu is getting its data from the generated files. Did you try to export and restart your engine? And maybe you should test if this problem happen with new centreon version 2.7.4 too.

**Comment by GhilesKDH** [comment]
Hi, thank you for the replay
Yes i restarted the engine:
i have the hostgroup défined in the file generated: /usr/share/centreon/filesGeneration/nagiosCFG/10/hostgroups.cfg
 i see them in the configuration menu, and in the filter of host or service configuration (configuration menu),  but i don't see them in the hostgroup fiter of monitoring menu.
thank you,

**Comment by Sims24** [comment]
Hi Ghiles, 

Since upgrade to 2.7, that could probably comes from mismatch between Centreon and your engine/broker options. 

Please check that your engine version is 1.5.0 and that your broker version >= 2.11

**Comment by GhilesKDH** [comment]
Hi simon, 
We don't upgrade to 2.7 yet..we are always in 2.6.6.
We will try to upgrade to 2.7 this week and we'll see if that fixes the problem
thank you,

**Comment by Sims24** [comment]
Ghiles, 

I mean that if one of your poller is in one of the version mentionned above, then some hostgroup that are only used on it will not be available in monitoring filter. That's a "normal" and known behaviour. 

Engine and cbmod flow has some slight differences because we now are only using id for hostgroups and servicegroups (more efficient, breaking compatibility with ndo and Centreon < 2.7).

Let us know if it's OK after upgrade, pay attention to the release note containing special action regarding hostgroup. 

Regards
