### ISSUE TITLE
Problem with an hostname containing the "+" symbol

### ISSUE THREAD

**Issue by fredlacave** [centreon/centreon#4397]
With Centreon 2.7.3, an hostname containing the plus symbol leads to all sorts of problems ; no command from the service and host status details work worrectly (schedule downtime, acknowledge, ...).  The search boxes either don't work or replace the + symbols with spaces, etc.

**Comment by julienmathis** [comment]
Hello, 

It's not possible to use a + in object names because it's a special used by Regular Expression Matching. More information here : https://documentation.centreon.com/docs/centreon-engine/en/latest/user/configuration/advanced/time_saving_tricks_for_object_definitions.html#obj-def-tricks-service

BR
