### ISSUE TITLE
 Inherit contacts from host not properly working

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#4405]
Inheritance is working when you have a fresh install of CES. If you change some arguments, export it and enable "Inherit contacts from host" in one or more service elements it is not working anymore.

Our client has a contact group linked to the service and a single contact. The contact got the notify, the user(s) from the contact group does not get it. Unfortunately the option is not understandable by looking at the /etc/centreon-enginge/services.cfg file. The reason is, the Inheritance is not shown (even in the beginning when the function is working).

What options are there to isolate the problem? Can you explan the Inheritance more in detail, the documention has no details.

**Comment by julienmathis** [comment]
Hello, 

If you link the contact that is linked to the contact group directly to the service, does it receive the notification ? 

I don't think that the inheritance is your problem. If you check the help info, the inheritence option is explain like that : "Specify whether or not the service will inherit host's contacts and contactgroups (if no contacts or contactgroups are defined for the service)."

I think that your problem is a contact configuration problem. May be the notification options are not well configured in the contact object.

**Comment by lpinsivy** [comment]
Hello

Since Centreon Engine 1.4.15 the contacts notified are:

1. contacts and/or groups of contacts defined in service configuration
2. contacts and/or groups of contacts defined in service configuration and those from the template if "Contact additive inheritance" and "Contact group additive inheritance" are enabled.
3. contacts and groups of contacts from host if no contacts/contactgroups are defined on service and if "Contact additive inheritance" and "Contact group additive inheritance" are disabled.

The issue is that the option still available in Centreon web GUI but not active because the call to the code is commented into Centreon sources. We keeped the options to have the possibility to enable function into Centreon sources for Centreon Engine < 1.4.15.

We will work on a new system to bypass the service or template of service contacts/contactgroups configuration by enabling the "Inherit contacts from host" option.

Do you agree with this new mechanism?
