### ISSUE TITLE
Downtimes ponctuels - Erreur de Timezone

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4443]
Bonjour,
Il y a un bug avec les downtimes ponctuels.
Ceux-ci se basent sur la timezone indiquée dans le fichier php.ini.

Les downtimes récurrents, quand à eux, se base sur : 
- La Timezone de l'hôte
- La Timezone de l'interface (Administration - Parameters - Centreon UI)

Est-ce que la modification pourrait-être faite ?
PS : Problème reproduit en 2.7.1 / 2.7.3 / 2.7.4
Cdlt

**Comment by garnier-quentin** [comment]
Timezone for not regular downtime are based on user timezone. But not in the right way.
I'm in Europe/Paris hour for my user. I want to set a downtime to 4pm (so UTC time is 2pm). In the interface, i have the right time 4pm and 2 minutes. But the downtime will be active at 6 pm and 2 minutes.

From the picker javascript (status/Services/serviceJS.php), we have 4pm and 2 minutes. It goes in the method 'AddSvcDowntime' (class/centreonExternalCommand.class.php) with 4pm and 2 minutes. It goes in following code:
```
 if($host_or_centreon_time == "0"){
            $start_time = $this->GMT->getUTCDateFromString($start);
            $end_time = $this->GMT->getUTCDateFromString($end);
  }
```

I have 'Etc/UTC' in my php.ini. So we will get the unix timestamp from 4pm in UTC ($sDate = new DateTime($date)). And after we set the timezone to Europe/Paris and get the timestamp. So that's why i have 6pm eventually.

With the following code it's working (only for the case!!! Don't apply it!):
```
 if (isset($date) && isset($gmt)) {
            if (!is_numeric($date)) {
                $sDate = new DateTime($date, new DateTimeZone($this->getActiveTimezone($gmt)));
            } else {
                $sDate = new DateTime();
                $sDate->setTimestamp($date);
            }

            #$sDate->setTimezone(new DateTimeZone($this->getActiveTimezone($gmt)));

            $return = $sDate->getTimestamp();
        }

```

**Comment by lpinsivy** [comment]
Quentin,

The correction should be:

```
$sDate->setTimezone(new DateTimeZone($this->getActiveTimezone($gmt)));
$iTimestamp = $sDate->getTimestamp();
$sOffset = $sDate->getOffset();
$return = $iTimestamp + ($sOffset * $reverseOffset);
```

**Comment by querwin** [comment]
I do this test : 
- local hour : 15h17 (Paris)
- user hour in Centreon : 14h17 (London)

I create a downtime on a service with : start hour : 16h17 and end hour : 16h20

As a result, I have : 
start of the downtime (local hour) : 15h17

So I don't understand which timezone we use in this case
