### ISSUE TITLE
upgrade failed from 2.5.4 to 2.6.6 or 2.7.3

### ISSUE THREAD

**Issue by mmiat** [centreon/centreon#4497]
I've tried to upgrade from 2.5.4
first I tried to update to 2.7.3, but it needs system upgrade too, I tried but system didn't start any more :(
so I've tried to update to 2.6.6, it seems because I can access centreon web interface, but I've a lot of errors, for example:
- Use of uninitialized value in concatenation (.) or string at /usr/local/nagios/libexec/check_centreon_snmp_traffic line 280.
- SNMP REQUEST ERROR : Received noSuchName(2) error-status at error-index 1. Cases: 1) SNMP not working. 2) specify the disk name when option -n is used. 3) Disk not exist. 4) Delete cache file '/var/lib/centreon/centplugins/remote_storage_cache_192.168.10.
- Use of uninitialized value $argv[0] in pattern match (m//) at /usr/local/share/perl/5.10.0/Net/SNMP.pm line 1203.
- SNMP TABLE ERROR : The base OBJECT IDENTIFIER "" is expected in dotted decimal notation.
- etc etc

is there some pre-requisites I need that is different from 2.5.4 to 2.6.6?
thanks

**Comment by mmiat** [comment]
maybe it's a problem with requirements. where can I found them?

**Comment by mmiat** [comment]
if I install a clear centreon in a new clear environment, can I move my hosts/services configuration? thanks

**Comment by gvieira-nr** [comment]
I found some checks in centreons snmp to be buggy and it's been that way for a long time. I just correct it on every install/reinstall. I don't know if you use debian or redhat but if debian, i highly recommend using the installation script from https://github.com/GreenCom-Networks/centreon-install which does a full install of centreon and all in 1 bash script.
from your old installation, just export your whole config using the CLAPI if you can and then import it. there will still be some stuff you'll have to probably get it going but it'll be a nice clean install.

2.7.x has a problem with snmp traps but there's a small patch for it, it'll be fixed in 2.8 as I tested it and works but it not production ready or released..

**Comment by mmiat** [comment]
I've Lenny (Debian 5), and I've tried to download and installa CLAPI, all seems ok but nothing happens when I try to launch "./centreon -u admin -p centreon -a POLLERLIST" or "./centreon -u admin -p centreon -e > /tmp/clapi-export.txt"

so, if I upgrade my Debian to Jessie, and then download and launch centreon-install, it UPGRADE my running centreon so I can keep my configuration? thanks

**Comment by gvieira-nr** [comment]
I wouldn't try it if the versions was _way_ off. you're better off exporting the configuration using the cliapi and importing into the new one. At least this way you have 2 machines available and can test the new one until it works like the original one does.

**Comment by mmiat** [comment]
my problem is that I can't upgrade neither os neither centreon...

**Comment by snaki4** [comment]
your problem is SNMP.pm  .... Debian based distro use SNMP,pm 6.X (libnet-snmp-perl), while centreon is more RedHad oriented where 5.5 is still in use.
