### ISSUE TITLE
Redirection after login page

### ISSUE THREAD

**Issue by bcournaud** [centreon/centreon#4594]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CES

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Firefox 48.0 / Ubuntu

**Steps to reproduce the issue:**
1. Go on the monitoring page of a service
2. Copy the URL of the page
3. Open a new page in private navigation
4. Open the URL previously copied
5. You will arrived on the login page
6. Enter your credentials and click "Connect"

**Describe the results you received:**
You arrive and the main page of Centreon Web (custom views).

**Describe the results you expected:**
You should arrive on the monitoring page of the service

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
OK in Centreon, web 2.8.5

**Comment by bcournaud** [comment]
No way! This is fucking awsome! Thanks :D

**Comment by bcournaud** [comment]
Hello,

I tried this fix on Centreon Web 2.8.9 and it still doesn't seem to work :'-(

**Comment by jadzdotcom** [comment]
I believe this is still an issue even in the latest 19.10

Steps to reproduce using the Centreon Demo Site

1. Open Incognito/Private Tab (to ensure you don't already have a session with demo.centreon.com)
2. Open https://demo.centreon.com/centreon/main.php?p=20201&o=svcd&host_name=srv-oracle-accounting&service_description=oracle-tablespace-SYSAUX
3. Login Page is Displayed with `redirect='p=20201&o=svcd&host_name=srv-oracle-accounting&service_description=oracle-tablespace-SYSAUX'` in the URL
4. Login
5. System Displays Custom Views instead of the originally requested URL.
