### ISSUE TITLE
Problem to display real-time page summary with IE 11

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#4601]
---
## BUG REPORT INFORMATION

**Centreon Web version**: centreon-2.8.0-beta1

**Steps to reproduce the issue:**
1. Use IE11 and go to "Monitoring > Status Details"
2. Go to "Services Grid" or "Services by Hostgroup" or "Services by Servicegroup" or "Hostgroups Summary"

**Describe the results you received:**
![screen_ie_problem](https://cloud.githubusercontent.com/assets/9079781/17623049/67322ffa-609e-11e6-8468-d9e10172381a.png)

**Describe the results you expected:**
Well-aligned :)

**Comment by zd14a** [comment]
Hi,

we have the same problem with our installation. The problem appears due to the way the objects (which represents the services links) were created in the IE. It's:

`<a class="infobulle link_popup_volante margin_right" id="service-4355-5394" href="main.php?o=svcd&amp;p=202&amp;host_name=hostname&amp;service_description=ping"><span class="state_badge service_ok">ping</span></a></td>`

While in other browsers it's:

`<a id="service-2680-23517" class="infobulle link_popup_volante margin_right" href="main.php?o=svcd&amp;p=202&amp;host_name=hostname&amp;service_description=ping"><span class="state_badge service_ok"></span>ping</a>`

As you can see the name of the service is in other browsers not part of the status badge span but of the link itself. So it can claim the whole width of the text+badge and not only the 10px of the badge.

Currently we have a workaround for the IE11, which displays the services not longer side by side but one above another. Not beautiful (not at all!!), but at least you can read it:
`_:-ms-fullscreen, :root td.ListColLeft > a.infobulle  > .state_badge:before {  content: "\00a0\00a0\00a0\00a0"; }`
`_:-ms-fullscreen, :root td.ListColLeft > a.infobulle.link_popup_volante.margin_right { display:block; width:200px;}`

A fix by centreon would be highly appreciated. Thanks in advance :)

**Comment by cgagnaire** [comment]
Please use latest Edge versions (the Chrome-like one) :)
