### ISSUE TITLE
Beta 2.8 Help Messages in Host configuration

### ISSUE THREAD

**Issue by querwin** [centreon/centreon#4618]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.8.0-Beta1

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CentOS-6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMWare

**Steps to reproduce the issue:**
1. Go in host configuration and add or update an host

**Describe the results you received:**
- Recovery notification delay -> no message
- Severity level -> message is "severity level"
- Geo coordinates -> no message
- Status -> no messages
- Comments -> no messages

**Comment by sbraz** [comment]
@lpinsivy The message for "Recovery notification delay" is the same as the one from "First notification delay".

**Comment by lpinsivy** [comment]
It should be corrected because help messages are differents:

Host - First notification delay: Define the number of "time units" to wait before sending out the first problem notification when this host enters a non-UP state. With the default time unit of 60s, this number will mean multiples of 1 minute. If you set this value to 0, monitoring engine will start sending out notifications immediately.

Host - Recovery notification delay: Define the number of "time units" to wait before sending out the recovery notification when this host enters an UP state. The default time unit is 0 (this number will mean multiples of 1 minute). If you set this value to 0, monitoring engine will start sending out notifications immediately.

Service - First notification delay: Define the number of "time units" to wait before sending out the first problem notification when this service enters a non-OK state. With the default time unit of 60s, this number will mean multiples of 1 minute. If you set this value to 0, monitoring engine will start sending out notifications immediately.

Service - Recovery notification delay: Define the number of "time units" to wait before sending out the recovery notification when this service enters an OK state. The default time unit is 0 (this number will mean multiples of 1 minute). If you set this value to 0, monitoring engine will start sending out notifications immediately.
