### ISSUE TITLE
Alignement des input box dans l'édition des services et hôtes

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon#4657]
**Centreon Web version**: 2.7.6

**Centreon Engine version**: Last

**Centreon Broker version**: Last

**OS**: CentOS 6

Bonjour,

Sur notre plateforme de test nous sommes en train de tester la version 2.7.6 (migration depuis 2.6.6). Je remarque quelques soucis d'ergonomie : 

- Comme montré dans la capture d'écran ci-jointe (issue de votre plateforme de démo), les champs de saisies ne sont pas alignées à cause des croix à gauche, ça casse la linéarité des formulaires et ça en devient gênant pour la lecture.

- Le nom du service n'apparait qu'en 2e position alors qu'on est en train d'éditer un service... Il faudrait que celui-ci reprenne sa place initiale en premier argument, et seulement ensuite les hôtes auxquels il est rattaché.

- Impossible de recherche un groupe d'hôtes ou de services dans la vue "Performances". C'est dommage de ne pas laisser cette possibilité.

![alignement-input-box](https://cloud.githubusercontent.com/assets/14218330/18052481/eec3de00-6dfa-11e6-9086-b6fbae1d7b71.PNG)

Merci par avance pour vos réponses. :)

**Comment by lpinsivy** [comment]
Hi,

Thank you for your feedbacks. Can you create one issue per idea ?

* Ok for the idea to align fields

* Ok for idea to move name of service fisrt but create a new ticket

* Yes we had changed the mechanism to add chart. The idea is to display only needed chart. That's why you have first to select a group of chart by host, hostgroup or servicegroup and then to add chart by chart.

**Comment by Hellnino18** [comment]
The 2 first ideas have there own issues. The last, is already opened.

I think you can close this one.

Thanks.
