### ISSUE TITLE
influxdb configuration

### ISSUE THREAD

**Issue by george-vieira** [centreon/centreon#4772]
**Centreon Web version**: 2.7.4

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.0

**OS**: 
debian jessie

I have the influxdb.so module built and loaded according to the Poller Statistic page and was wondering should this be workable for the above version and if so, besides the basic XML configuration as shown on Issue #4058 what else needs to be done to push metrics to influxdb.

I thought it would load the xml from my /usr/local/centreon-brokers/etc where the current central-broker.xml, central-module.xml and central-rrd.xml are but not sure how to get these all glued together.

Any more documentation on this this is done end to end possible?

**Comment by dgarandel** [comment]
With centreon-broker 3.0.2-3 and influxdb 1.1.0 don't work with now log into central-broker-master.log 

{"error":"unable to parse 'STATUS,host=\"centeon-server\",service=\"Slowqueries\",index_id=\"7\",value=0 1480951061': invalid field format
Same for METRIC.

On influxdb connection 

INSERT STATUS,host="centeon-server",service="proc-ntpd",index_id="16",value=0 1480950952
ERR: {"error":"unable to parse 'STATUS,host=\"centeon-server\",service=\"proc-ntpd\",index_id=\"16\",value=0.1480950952': missing fields"}

The correct command is 

INSERT STATUS,host=centeon-server,service=proc-ntpd,index_id=16 value=0.1480950952

Don't add ',' before value and all tags do not content blank charaters.
And missing dot ('.') characters on value

**Comment by dgarandel** [comment]
Hello, 
Almost work. Now I'm in centreon-groker-influxdb 3.0.4-4 and Influxdb 1.1.1 (Same issue with 1.x)
Data's are correctly inserted into Influxdb database but still have a problem with "time" field.

You send insert command with "time" in unix timestamp format and Influxdb need Epoch format (And also convert into UTC timezone)

Ie of wrong insert 👍 
INSERT STATUS,host=centeon-server,service=proc-ntpd,index_id=16 value=0.11 1480950952

Ie with correct insert command 
INSERT STATUS,host=centeon-server,service=proc-ntpd,index_id=16 value=0.11 148095095200000

And trace from influxdb database
> influx
> use centreon
> >  SELECT "time","value" FROM "metrics.ethe-01-tc2-25434.Interface TenGigabitEthernet1/2/0.in" limit 3
name: metrics.ethe-01-tc2-25434.Interface TenGigabitEthernet1/2/0.in
time            value
----            -----
1483440198      6.34255e+06
1483440504      5.99187e+06
1483440798      2.28434e+06

Has you can see data's are now send by centreon-broker to Influxdb but stay a pb with "time" format.

And now try to get data's from curl access (Like using by Grafana, Kibana, ...)

# curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=centreon" --data-urlencode 'q=SELECT "value" FROM "metrics.ethe-01-tc2-25434.Interface TenGigabitEthernet1/2/0.in"'

[...]
 [
                            "1970-01-01T00:00:01.483617798Z",
                            3.00917e+06
                        ]
[...]

Has you can see "time" is not correctly converted because not in EPOCH format.

**Comment by george-vieira** [comment]
I've never had broker 3.x working with centreon 2.7.x and assume there's some sort of relationship between these versions so I assume broker 3.x only works with centreon 2.8? When I tried upgrading there was all sorts of problems so stayed with 2.7 for now.
Your examples I assume won't work with my version as you keep mentioning broker 3, can any of this work with centreon 2.7.x atm?

For the time being, I've resorted to using passive mode using a project I developed (centreon-agent) and works well which manages passive monitoring and alerts to central only on status changes (bit like nagios but more flexible) and adding a separate function to pull the metrics from service interval checks and send those separately via the metrics handler (ie influxdb, prometheus, etc) even when no status changes.

It would be still nice to get 2.7 working with influx or prometheus (which we use at work) as it'll be ages before we can upgrade to 2.8 safely.

**Comment by dgarandel** [comment]
I'm full right with you. The last version of centreon and so centreon-broker doesn't work with stable centreon 2.7. Centreon team said to do not use last ces-3.4 repository with centreon 2.7 in production (specialy if you use module/extention). I tested also and yes don't work and cannot install easyly.
So I tested this centreon-broker 3.x on dev and dedicated server with ces-3.4 repository (So with centreon 2.8 and last broker 3.0.x). I do that for debuging the centreon-broker-influxdb.
This is why I add this note in this issue. broker-influxdb work better but still have a "little" problem. Data's are written in influxdb (so it's better than last version) but write incorrectly the time value. Influxdb need to be written with epoch format and not in unix timestamp format.

So now (after corrected broker-influxb by Centreon team) and without made any change on your production server with centreon 2.7 you can add a separate server with ces-3.4 repository and launch a "yum install centreonbroker centreon-broker-influxdb". On your centreon 2.7 just add a broker output to send perfdata to tcp port to new server. This new server with cbd listening on this port and an output broker write data's to influxdb server.
The cbd xml file must be created manually (don't work with centreon interface) to add infulxdb output section.
This post show a correct example of xml file for influxdb : https://github.com/centreon/centreon/issues/4058

**Comment by george-vieira** [comment]
my problem is my production server is mostly made up of over 220,000 passive service checks received every minute. This puts some load on the database (I've had to partition the logs and data-bin tables) and making use of the Monitoring->Event Logs completely useless as it hangs the UI and does huge query results. So I have to really limit sending results every minute which also means losing performance graphs every minute since these are tied together.
If I was somehow able to send to the broker only performance data, that would be great too but I think using influxdb/grafana for metrics is probably my end result.

I'm also using debian with centreon source compiled version thanks to a very easy install script written up by Greencom-Networks here https://github.com/GreenCom-Networks/centreon-install

**Comment by dgarandel** [comment]
I understand your problem. I had almost the same. Me too have 99% of services checks in passive mode.And yes Monitoring>Event-logs is problematic. rrd files is also now a problem with a lot of graphs. This is why I want also remove data_in, logs tables and also RRD files and rrdcached process.

For data performance I wait the next version of centreon-broker-influxdb. Stay now only the correction of time value. On my influxdb I receive data's from centreon (On dev server at this time).
After that on My 2 centreon master server I will put only one <output> section t send dataperf to influxdb and remove the 2 other putput section section. (Perfdata and rrd section). With this no data's will be send to data_in tables and no send to rrdcached.
For Monitoring>Event-logs I use my own notification process. All pollers send all notitiation to central centreon server to a specific tcp port. A daemon read these input and just write result into log files. With this I can grep|awk has I need. But also with a splunk-forwarder process these log files are send to Splunk server for analyze, report, etc... With this no need Centreon logs table.
This will reduce overhead, wait I/O, load, ....
And with 2 centreon central in pseudo cluster made by centreon-broker with haproxy on server I'm more secure 
Below my outpout section on xml file 👍 

My prod server (2.7.8) add an oupt to TCP/5672
My Dev server (With only centreon-broker-influxdb, No centreon) add 1 input to read 5672
And these output's to send to my influxdb server
And Grafana can centralize all different graphics tools
 <output>
  <name><![CDATA[influxdb]]></name>
  <cache><![CDATA[yes]]></cache>
  <db_host><![CDATA[ip-of-influxdb-server]]></db_host>
  <db_port><![CDATA[8086]]></db_port>
  <db_user><![CDATA[user-influxdb]]></db_user>
  <db_password><![CDATA[password]]></db_password>
  <db_name><![CDATA[centreon]]></db_name>
  <metrics_timeseries><![CDATA[metrics.$HOST$.$SERVICE$.$METRIC$]]></metrics_tim                                                                                        eseries>
  <status_timeseries><![CDATA[status.$HOST$.$SERVICE$]]></status_timeseries>
  <type><![CDATA[influxdb]]></type>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </metrics_column>
  <metrics_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[number]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </status_column>
  <status_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[number]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </status_column>
  <failover><![CDATA[influxdb-output-failover]]></failover>

This must be made manually because don't work with centreon interface

**Comment by george-vieira** [comment]
Centreon-Broker: 3.0.5
Centreon Web: 2.8.7

Still got timestamp issues with this. Also, entering metrics and status column is missing until you hide the output influxdb box by clicking it and then clicking it again to expand/expose all the fields and then the Metrics column boxes reappear.. little annoying but workaround.

I thought I saw timestamp was to be fixed in 3.0.4 of the broker?

**Comment by george-vieira** [comment]
Centreon Web version: 2.8.8

Centreon Engine version: 1.7.0

Centreon Broker version: 3.0.7

OS:
debian jessie

Upgraded now but still can't get proper influx data out. If I use $HOST$ it errors in detailed log with:
[1495769061] error:   influxdb: couldn't generate query for metric 1126: influxdb: could not find information on host 20
[1495769061] debug:   multiplexing: acknowledging 0 events from influxdb event queue
[1495769061] debug:   failover: reading event from multiplexing engine for endpoint 'influxdb'
[1495769061] debug:   failover: writing event of multiplexing engine to endpoint 'influxdb'
[1495769061] error:   influxdb: couldn't generate query for metric 1127: influxdb: could not find information on host 20
[1495769061] debug:   multiplexing: acknowledging 0 events from influxdb event queue
[1495769061] debug:   failover: reading event from multiplexing engine for endpoint 'influxdb'
[1495769061] debug:   failover: writing event of multiplexing engine to endpoint 'influxdb'
[1495769061] error:   influxdb: couldn't generate query for metric 1128: influxdb: could not find information on host 20

If I remove the tag $HOST$ it starts to work but the data is useless without knowing what host.
I can get posts to influxdb, tcpdump capture with grep as below:
centreon.metrics./ value=2070 1495769536
centreon.metrics.load1 value=0 1495769536
centreon.metrics.load5 value=0 1495769536
centreon.metrics.load15 value=0 1495769536
centreon.metrics.load1 value=0 1495769537
centreon.metrics.load5 value=0 1495769537
centreon.metrics.load15 value=0 1495769537
centreon.metrics./ value=1787 1495769537
centreon.metrics.debian--vg-root_rps value=0 1495769538
centreon.metrics.procs value=1 1495769540
centreon.metrics.offset value=-0.000509 1495769540
centreon.metrics.procs value=1 1495769540
centreon.metrics./ value=2373 1495769540

No status information and it appears $SERVICE$ doesn't work either:
[1495769601] error:   influxdb: couldn't generate query for status 43: influxdb: could not find information on service (17, 52)
[1495769601] error:   influxdb: couldn't generate query for status 185: influxdb: could not find information on service (30, 53)

Not sure if there's some other setting up is require to expose those macros/vars?
&lt;centreonBroker&gt;
 &lt;broker_id&gt;&lt;![CDATA[4]]&gt;&lt;/broker_id&gt;
 &lt;broker_name&gt;&lt;![CDATA[central-influxdb-master]]&gt;&lt;/broker_name&gt;
 &lt;poller_id&gt;&lt;![CDATA[1]]&gt;&lt;/poller_id&gt;
 &lt;poller_name&gt;&lt;![CDATA[Central]]&gt;&lt;/poller_name&gt;
 &lt;module_directory&gt;&lt;![CDATA[/usr/local/centreon-broker/lib/centreon-broker]]&gt;&lt;/module_directory&gt;
 &lt;log_timestamp&gt;&lt;![CDATA[0]]&gt;&lt;/log_timestamp&gt;
 &lt;log_thread_id&gt;&lt;![CDATA[0]]&gt;&lt;/log_thread_id&gt;
 &lt;event_queue_max_size&gt;&lt;![CDATA[100000]]&gt;&lt;/event_queue_max_size&gt;
 &lt;command_file&gt;&lt;![CDATA[]]&gt;&lt;/command_file&gt;
 &lt;cache_directory&gt;&lt;![CDATA[/var/lib/centreon-broker]]&gt;&lt;/cache_directory&gt;
 &lt;input&gt;
  &lt;name&gt;&lt;![CDATA[central-influxdb-master-input]]&gt;&lt;/name&gt;
  &lt;port&gt;&lt;![CDATA[5680]]&gt;&lt;/port&gt;
  &lt;protocol&gt;&lt;![CDATA[bbdo]]&gt;&lt;/protocol&gt;
  &lt;tls&gt;&lt;![CDATA[auto]]&gt;&lt;/tls&gt;
  &lt;negotiation&gt;&lt;![CDATA[yes]]&gt;&lt;/negotiation&gt;
  &lt;one_peer_retention_mode&gt;&lt;![CDATA[no]]&gt;&lt;/one_peer_retention_mode&gt;
  &lt;compression&gt;&lt;![CDATA[auto]]&gt;&lt;/compression&gt;
  &lt;type&gt;&lt;![CDATA[ipv4]]&gt;&lt;/type&gt;
 &lt;/input&gt;
 &lt;logger&gt;
  &lt;name&gt;&lt;![CDATA[/var/log/centreon-broker/central-influxdb-master.log]]&gt;&lt;/name&gt;
  &lt;config&gt;&lt;![CDATA[yes]]&gt;&lt;/config&gt;
  &lt;debug&gt;&lt;![CDATA[yes]]&gt;&lt;/debug&gt;
  &lt;error&gt;&lt;![CDATA[yes]]&gt;&lt;/error&gt;
  &lt;info&gt;&lt;![CDATA[yes]]&gt;&lt;/info&gt;
  &lt;level&gt;&lt;![CDATA[high]]&gt;&lt;/level&gt;
  &lt;type&gt;&lt;![CDATA[file]]&gt;&lt;/type&gt;
 &lt;/logger&gt;
 &lt;output&gt;
  &lt;name&gt;&lt;![CDATA[influxdb]]&gt;&lt;/name&gt;
  &lt;cache&gt;&lt;![CDATA[no]]&gt;&lt;/cache&gt;
  &lt;db_host&gt;&lt;![CDATA[metrics]]&gt;&lt;/db_host&gt;
  &lt;db_port&gt;&lt;![CDATA[8086]]&gt;&lt;/db_port&gt;
  &lt;db_user&gt;&lt;![CDATA[centreon]]&gt;&lt;/db_user&gt;
  &lt;db_password&gt;&lt;![CDATA[centreon]]&gt;&lt;/db_password&gt;
  &lt;db_name&gt;&lt;![CDATA[monitoring]]&gt;&lt;/db_name&gt;
  &lt;metrics_timeseries&gt;&lt;![CDATA[centreon.metrics.$METRIC$]]&gt;&lt;/metrics_timeseries&gt;
  &lt;status_timeseries&gt;&lt;![CDATA[centreon.metrics.status]]&gt;&lt;/status_timeseries&gt;
  &lt;type&gt;&lt;![CDATA[influxdb]]&gt;&lt;/type&gt;
  &lt;metrics_column&gt;
   &lt;is_tag&gt;&lt;![CDATA[false]]&gt;&lt;/is_tag&gt;
   &lt;type&gt;&lt;![CDATA[number]]&gt;&lt;/type&gt;
   &lt;value&gt;&lt;![CDATA[$VALUE$]]&gt;&lt;/value&gt;
   &lt;name&gt;&lt;![CDATA[value]]&gt;&lt;/name&gt;
  &lt;/metrics_column&gt;
  &lt;status_column&gt;
   &lt;is_tag&gt;&lt;![CDATA[false]]&gt;&lt;/is_tag&gt;
   &lt;type&gt;&lt;![CDATA[number]]&gt;&lt;/type&gt;
   &lt;value&gt;&lt;![CDATA[$VALUE$]]&gt;&lt;/value&gt;
   &lt;name&gt;&lt;![CDATA[value]]&gt;&lt;/name&gt;
  &lt;/status_column&gt;
  &lt;status_column&gt;
   &lt;is_tag&gt;&lt;![CDATA[true]]&gt;&lt;/is_tag&gt;
   &lt;type&gt;&lt;![CDATA[string]]&gt;&lt;/type&gt;
   &lt;value&gt;&lt;![CDATA[$SERVICE$]]&gt;&lt;/value&gt;
   &lt;name&gt;&lt;![CDATA[service]]&gt;&lt;/name&gt;
  &lt;/status_column&gt;
 &lt;/output&gt;
&lt;/centreonBroker&gt;

**Comment by ErrafayM** [comment]
I have same issue , and i'm using latest Centreon version... , any news about this one ?

**Comment by dgarandel** [comment]
For me it's working fine.
Centreon 2.8.9, centreon-broker 3.0.5 (work well since 3.0.4), centreon-engine 1.7.1

And bellow my configuration 

 <output>
  <name><![CDATA[influxdb]]></name>
  <cache><![CDATA[yes]]></cache>
  <db_host><![CDATA[my-remote-ip]]></db_host>
  <db_port><![CDATA[8086]]></db_port>
  <db_user><![CDATA[centreon]]></db_user>
  <db_password><![CDATA[xxxxx]></db_password>
  <db_name><![CDATA[centreon]]></db_name>
  <metrics_timeseries><![CDATA[metrics.$SERVICE$]]></metrics_timeseries>
  <status_timeseries><![CDATA[status.$SERVICE$]]></status_timeseries>
  <type><![CDATA[influxdb]]></type>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[number]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[number]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$METRIC$]]></value>
   <name><![CDATA[metric]]></name>
  </metrics_column>
 </output>

![influxdb](https://user-images.githubusercontent.com/12425523/29412106-aa7ce872-8357-11e7-8180-7700b57a5619.jpg)

**Comment by dgarandel** [comment]
<output>
  <name><![CDATA[influxdb]]></name>
  <cache><![CDATA[yes]]></cache>
  <db_host><![CDATA[my-remote-ip]]></db_host>
  <db_port><![CDATA[8086]]></db_port>
  <db_user><![CDATA[root]]></db_user>
  <db_password><![CDATA[xxxx]]></db_password>
  <db_name><![CDATA[centreon]]></db_name>
  <metrics_timeseries><![CDATA[metrics.$SERVICE$]]></metrics_timeseries>
  <status_timeseries><![CDATA[status.$SERVICE$]]></status_timeseries>
  <type><![CDATA[influxdb]]></type>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[number]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[number]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$METRIC$]]></value>
   <name><![CDATA[metric]]></name>
  </metrics_column>
 </output>

**Comment by ErrafayM** [comment]
Can you please provide your configuration ?

**Comment by dgarandel** [comment]
Copy/paste strange. In my last comment you must clic on 'edit comment' icon to see my configuration
In my conf I add 'host' metrics_column. I think it's better for creating grafana graph by applied more filters

**Comment by ErrafayM** [comment]
Can you take a screenshot of the configuration, if that won't bother you ? , i can't find edit your comment.
thank you again, i'm also using grafana for graphics.

**Comment by dgarandel** [comment]
<output>
  <name><![CDATA[influxdb]]></name>
  <cache><![CDATA[yes]]></cache>
  <db_host><![CDATA[my-remote-ip]]></db_host>
  <db_port><![CDATA[8086]]></db_port>
  <db_user><![CDATA[centreon]]></db_user>
  <db_password><![CDATA[xxxx]]></db_password>
  <db_name><![CDATA[centreon]]></db_name>
  <metrics_timeseries><![CDATA[metrics.$SERVICE$]]></metrics_timeseries>
  <status_timeseries><![CDATA[status.$SERVICE$]]></status_timeseries>
  <type><![CDATA[influxdb]]></type>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[number]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[number]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$METRIC$]]></value>
   <name><![CDATA[metric]]></name>
  </metrics_column>
 </output>

**Comment by dgarandel** [comment]
![broker-influxdb](https://user-images.githubusercontent.com/12425523/29448246-f1fb5032-83f5-11e7-9262-2eeedf6ba158.jpg)

**Comment by ErrafayM** [comment]
Thanks you, its working !
