### ISSUE TITLE
Graph scale values not working

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon#4815]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.1

**Centreon Engine version**: 1.6.2

**Centreon Broker version**: 3.0.2

**OS**: CentOS 6.6
![graph-disk](https://cloud.githubusercontent.com/assets/14218330/20920167/2dc49742-bb9f-11e6-8ad2-651c4012228d.PNG)
![graph-memoire](https://cloud.githubusercontent.com/assets/14218330/20920168/2dc64c7c-bb9f-11e6-843a-0cd142e5cbc7.PNG)

Hi,

I'm trying the new Centreon 2.8.1 and it looks very great ! But I think there is a problem with the "Graph scale values" in graph templates when there is 2 metrics different.

In my example, I have the percent of inode used on the same graph that used disl in bytes. The used metric is not scaled in Giga (cf screen).

I also join another graph where the graph scale works (all metrics is in bytes).

Thanks in advance for your help !

**Comment by masgo** [comment]
I am having the same(?) or a similar issue. In my case the problem is that the right y-axis is not scaled correctly (the maximum value shown is much higher than any measured value) and also the metric which should be on the second axis is not drawn at all. 
![screenshot-centreon-axis-problems](https://cloud.githubusercontent.com/assets/1336992/22460635/150f7428-e7a6-11e6-8e1b-1fbf72faaafa.png)
This is an http test which queries a website to check if the server works. The time (blue on the right y-axis) is the query time which is usually around 20ms.

**Comment by kduret** [comment]
related #5202

**Comment by Tpo76** [comment]
Display some strange value in the ordinate axis
![image](https://cloud.githubusercontent.com/assets/11980015/26319199/57da98b2-3f1e-11e7-8053-7fff76f71954.png)
The percent at the left have some wrong value. it normaly % but we have  90.000B % on the ordinate axis

**Comment by thiuyendang** [comment]
refer to #5202
