### ISSUE TITLE
insertCmd-Tps.sql

### ISSUE THREAD

**Issue by leo29041982** [centreon/centreon#4836]
**Centreon Web version**: 
2.8.1

www/install/insertCmd-Tps.sql doesn't exist, no Template Commands are created.

**Comment by julienmathis** [comment]
Hello, 

Since version 2.8.0, Centreon base config is empty. You can install commands and templates via plugins packs. You can do it following this documentation : https://static.centreon.com/wp-content/uploads/2016/11/centreon_imp_quick_start_en_2016_09.pdf

Old commands and templates were deprecated. Now you have a better configuration with centreon plugins packs.

I hope it helps you.
