### ISSUE TITLE
[2.8.2] graph issue (not bug, only bad configuration)

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#4860]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. create a service based on linux diskIO template
2. let all the default parameters
3. no graph .... 

**Describe the results you received:**
graph error

**Describe the results you expected:**
a working graph ....

**Additional information you think important (e.g. issue happens only occasionally):**
![capture d ecran de 2016-12-29 16-59-35](https://cloud.githubusercontent.com/assets/5741421/21563118/c7c3d348-ce7e-11e6-8723-80a8f5fd7d5f.png)

The centreon-plugin behind this check has been poorly designed to return as many metrics as it can which is really a bad practice. The result is that this plugin became useless in it's default configuration with the new graph library. It should be better to return less metrics by default and let the user add the others by himself.

**Comment by florian-asche** [comment]
The graph only dont work in mouseover mode. If you follow the link, it will work. But that is not a solution yes. I think, the default configuration should be changed, to display only the disks that are specified in the configuration. A default disk chould be "/".

**Comment by masgo** [comment]
This is not really a template problem, but it is caused by the new graph style which can not deal with many metrics. The old one worked flawlessly. It could show the the per-port traffic graph of a 52 port switch flawlessly. The new one fails even with a 24 port switch.

**Comment by florian-asche** [comment]
And the new one is much slower :(

**Comment by masgo** [comment]
The speed seems to depend. If the slowest part was the network (e.g., slow VPN over 3G) then the new one seems to be a little faster. But the new one definitely causes a much higher load on the browser itself.

**Comment by lpinsivy** [comment]
Yes we blocked chart with many curves due to hight browser load. But normally a button allows you to display graph if wanted in "Performance menu".

The best way is to filter needed values in template of service instead of collect all data

**Comment by masgo** [comment]
This is clearly a step backwards since it worked like a charm before.

For my example of monitoring a switch, all the data is important. If the switch has 52 Ports (i.e., 48 Ports + 4x SFP), then I want to know the state and traffic of all 52 Ports. (Actually, with VLANs and LAGs there are even more values wo monitor). If some port becomes overloaded of causes unusual high traffic, then I want to know which one it is. 

The same applies for per-subnet traffic in routers, for disk-I/O when I have many disks, for temperature values when I have many sensors, etc. etc. .... If the thing I am monitoring would be small and consist of only a few things to monitor, then I would not need a monitoring solution like centreon. 

What I could live with, would be a top-k output. So, when I monitor a switch, I do not care about all ports, but only about the high-traffic ports. But I can not know beforehand which ports will have the high traffic.

**Comment by julienmathis** [comment]
So having 104 lines on a graph is useful for you ? It's a step backward if you can read cleared and efficiently the content of the graph... It's not the case. 

We decide to stop graphing this kind of datas. Last day I see a graph with 900 metrics... It was causing overload on the servers...

So for me the only bug here is the command of the plugin.

**Comment by masgo** [comment]
Yes, it is useful. Here is an example of a traffic graph of a switch with 52 ports.
![switch-traffic-example](https://cloud.githubusercontent.com/assets/1336992/22955117/ba58dba2-f31a-11e6-8a54-6902de8bc155.png)

I just need one quick look to recognize that something happened on Thursday. (In this case it was a misconfiguration which lead to traffic being send over the wrong path)

You can also easily see the maximum bandwidth of this period. You can see that the "normal" usage is very low (most connected devices are VoIP phones = low traffic). In other scenarios you could easily see if two ports have traffic spikes at the same time. etc. etc. - Do not underestimate the power of humans when it comes to pattern recognition.

And since it is possible to filter out some graphs, I can then go ahead and focus on the ports which are of interest.

**Comment by lpinsivy** [comment]
We added an option to force display of curves
