### ISSUE TITLE
Dashboard - Hosts or Services Widget is to small

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#4871]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
Centreon 2.8.2
**Centreon Engine version**: 
Centreon Engine 1.6.2
**Centreon Broker version**: 
Centreon Broker 3.0.3
**OS**: 
CentOS release 6.8 (Final)
**Additional environment details (AWS, VirtualBox, physical, etc.):**
KVM

**Steps to reproduce the issue:**
1. Open Centreon
2. Goto Custom Views

**Describe the results you received:**
The Host- or Services List is not full displayed.

**Describe the results you expected:**
Complete List on one Screen (scrolling is ok)

**Additional information you think important (e.g. issue happens only occasionally):**
See here: https://github.com/centreon/centreon/issues/4224 (closed)

**Comment by thomas-thenet** [comment]
Hello,

We have the same problem in the service monitoring view with parameter warning, critical or unkown.

For correct it add this code after line 359 in /usr/share/centreon/www/include/home/customViews/index.php

`jQuery(".viewBody .widgetBody .portlet .portlet-content iframe").css("height",window.innerHeight);`

This correction correct it in all web browser.

Thank you.

**Comment by kozfelipe** [comment]
Hi,
I got the same issue after upgrading Service Monitoring Widget to 1.6.2

![image](https://user-images.githubusercontent.com/25208457/41304874-b6b75c7c-6e47-11e8-9a42-eef6563c8c81.png)

iframe widget_7_32(index.php)

**Comment by kozfelipe** [comment]
mismatch file path at iframe causing delay on widget resize:
![image](https://user-images.githubusercontent.com/25208457/41855107-2fd246b0-7868-11e8-84ea-768e824a86d2.png)

the same issue may be applied to the other widgets:

![image](https://user-images.githubusercontent.com/25208457/41855273-95687904-7868-11e8-9b8e-41fbb3e35119.png)

the web page references to /centreon/src/data_js.js instead of /centreon/widgets/service-monitoring/src/data_js.js

**Comment by Moujimouja** [comment]
Hi,

Seems that this request is not valid anymore. 

I close it, don't hesitate to re-open if you still have the issue.
