### ISSUE TITLE
[BUG] Configure Downtime - Blank page for user submitted to ACLs

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4952]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.3
**Centreon Engine version**: 1.7.0
**Centreon Broker version**: 3.0.3

**Steps to reproduce the issue:**
1. In "Administration > ACL > Menus Access", add ACLs for "Monitoring - Downtimes - Downtimes"
2. Connect to Centreon with user submitted to ACLs
3. Go in "Monitoring - Downtimes - Downtimes - Add a Downtime"
4. Blank page

**Describe the results you received:**
Blank page

**Describe the results you expected:**
There should be a window to configure downtimes

Best Regards

**Comment by f-amundi** [comment]
Hello,

In ./www/include/monitoring/downtime/AddDowntime.php

Look like replacing : 
if (!$centreon->user->access->checkAction("schedule_downtime")) {
with
if (!$centreon->user->access->checkAction("service_schedule_downtime")) {

Fix the issue.
Regards,

**Comment by shiraazlall** [comment]
Im new to Github, so sorry if Im putting this in the wrong place, but I was wondering if the fix should be different. 

Currently the fix is to change the line to
`if (!$centreon->user->access->checkAction("service_schedule_downtime")) {`
but that means that a user should have access to "Schedule downtime for a service" Action ACL item (service_schedule_downtime)

I would think that a user should be able to get to the downtime page if he has access to just the "Schedule downtime for a host" Action ACL item (host_schedule_downtime). This would mean that the fix should look different. 

If you want to enforce that the user have EITHER "Schedule downtime for a host" OR "Schedule downtime for a service"
`if (!$centreon->user->access->checkAction("host_schedule_downtime") && !$centreon->user->access->checkAction("service_schedule_downtime")) {`

If you want to enforce that the user must have BOTH "Schedule downtime for a host" AND "Schedule downtime for a service"
`if (!$centreon->user->access->checkAction("host_schedule_downtime") || !$centreon->user->access->checkAction("service_schedule_downtime")) {`

Personally I like the EITHER option, so thats what Im using in my environment. Anyways, hope this helps someone else too.

**Comment by cancom-monitoring-parschalk** [comment]
Question:
Is it normal that a Non-Admin User can set a downtime for a Satellite or the Central ? 
For us is a Security Gap.

BTW The workaround work for us. Thanks.
