### ISSUE TITLE
Disable graphics for some service

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4961]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 2.11.5

**OS**: Redhat 6.8

I would like for some service not to activate the graphics, so I put the option "Process Perf Data" to No for this service. 
But the graph is still present, even after deletion it is rebuilt.

**Comment by nowx-gh** [comment]
same here. w'd like to disable graphs for some service checks.

**Comment by DonKiShoot** [comment]
Still present in 18.10.2
Can we have a choice option like "process perfdata" in service config to not taking care of perfdata ?
The goal is to minimize data usage and boost performance.
Good for our planet to remove useless data and reduce cpu usage :-)

**Comment by lpinsivy** [comment]
The process perfdata is an old option of previsous centstorage process.
I change this to enhancement

**Comment by UrBnW** [comment]
Hi @lpinsivy, @cgagnaire, @Moujimouja, @bouda1,
Would also be glad to be able to disable graphs for some services, even better for some service templates.

There's an existing option, in  _Administration > Parameters > Data_, to hide _graphs of selected services_, but seems like this only hides the graph icons from the _Status Details > Services_ view, graphs are still visible in other views. In addition, performance data is still proceeded, feeding the database, which should be avoided in the context of a _disable_ option.

One thing though, broker would still have to feed [Stream Connectors](https://github.com/centreon/centreon-stream-connector-scripts) with this performance data (so that the metrics can properly sent elsewhere).

Many thanks !

**Comment by omercier** [comment]
Hi,
With all centreon plugins, you can use this argument to disable performance data (only text output is returned): `--output-ignore-perfdata`.
This will avoid having graphs on your services.
I hope this helps.
Regards
