### ISSUE TITLE
Centreon Broker stops each hours.

### ISSUE THREAD

**Issue by zskarman** [centreon/centreon#5080]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: OEL6.8
Our broker is stopping around each hours,
This environment is behind the LB.

Error is in the centreon-broker-master.log

**Comment by zskarman** [comment]
![brokerissue](https://cloud.githubusercontent.com/assets/24320218/23996841/44b93080-0a4f-11e7-922f-1d03a7da64f3.PNG)

**Comment by ganoze** [comment]
It seems that Centreon Broker cannot process incoming TCP connections as the peers are already disconnected. Could that be caused by your LB ?

In all cases I do not have enough information to investigate this issue. Could you tell me more about your setup if there is anything unusual ? Also could you also generate a full debug log of Centreon Broker when such errors occur ?

**Comment by zskarman** [comment]
same issue
https://github.com/centreon/centreon-broker/issues/90
plus when we removed the TLS option from broker it works.

**Comment by zskarman** [comment]
if we remove the TLS option it works.

![tls](https://cloud.githubusercontent.com/assets/24320218/24491746/e82e6d1e-1528-11e7-874c-a3a84a9d9e64.PNG)

Could you pls give me any idea what should be the issue with the gnutls?
Rgs, Zsolt

**Comment by ganoze** [comment]
Could you checkout the module documentation that I updated few days ago ?

https://github.com/centreon/centreon-broker/blob/master/doc/user/modules.rst

Let me know if that helps you configure the TLS properly or not.
