### ISSUE TITLE
[2.7.10] The list of commands does not appear when adding a service

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#5229]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.10

**Centreon Engine version**: 1.5.3

**Centreon Broker version**: 2.11.8

**OS**: Centreon 3.3

After upgrade 2.7.8

The command list does not appear when you want to add a command to a service

![install_glpi2017-05-17_09-20-05_am](https://cloud.githubusercontent.com/assets/12350746/26142699/0adf37c4-3ae2-11e7-8c3f-7724712a66a8.png)

**Comment by Laexar** [comment]
Hi,

The problem is line 73 in /usr/share/centreon/www/include/common/webServices/rest/centreon_configuration_command.class.php : 

The column command_activate does not seem to exist anymore in the command table for centreon database.
So you basically just have to replace : 
$queryCommand .= "AND command_type = ? AND command_activate = 1 ";
by : 
$queryCommand .= "AND command_type = ? ";
