### ISSUE TITLE
[2.7.10] Command listing unavailable in connector definition

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5234]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.10

**Centreon Engine version**: N/A

**Centreon Broker version**: N/A

**OS**: N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**: N/A

**Steps to reproduce the issue:**
1. Go to "Configuration  >  Commands  >  Connectors"
2. Edit a connector
3. Click on "Used by command" selectbox

**Describe the results you received:**

No commands appear

**Describe the results you expected:**

Have the list of commands

![screenshot at mai 17 11-16-07](https://cloud.githubusercontent.com/assets/3351916/26146959/3e52239a-3af2-11e7-8109-140086d5440b.png)

**Comment by Laexar** [comment]
Hi,

The problem is line 73 in /usr/share/centreon/www/include/common/webServices/rest/centreon_configuration_command.class.php :

The column command_activate does not seem to exist anymore in the command table for centreon database.
So you basically just have to replace :
$queryCommand .= "AND command_type = ? AND command_activate = 1 ";
by :
$queryCommand .= "AND command_type = ? ";
