### ISSUE TITLE
'MySQL error : cannot connect to database centreon: Access denied for user' on fresh install

### ISSUE THREAD

**Issue by imnotme** [centreon/centreon#5323]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
centreon-web-2.8.8-4.el6.noarch

**Centreon Engine version**: 
centreon-engine-1.7.2-3.el6.x86_64

**Centreon Broker version**: 
centreon-broker-3.0.7-1.el6.x86_64

**OS**: 
CES ISO of 30/01/2017 01:30 PM
2.6.32-696.3.1.el6.x86_64

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ESXi 6.5

**Steps to reproduce the issue:**
1. Setup CES server (central with db)
2. Update with yum & reboot 
3. Log into web interface to finish setup
 * All options defaults settings
 * admin password is 'admin'
 * No mysql root password
 * centreon mysql password is 'centreon'
4. Log into admin panel
5. Discover that even the poller is not in the 'host' list
6. Look into /var/log/centreon/centcore.log

**Describe the results you received:**
/var/log/centreon/centcore.log :
2017-06-07 14:31:58 - MySQL error : cannot connect to database centreon: Access denied for user 'centreon'@'localhost' (using password: YES) (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)
2017-06-07 14:31:58 - MySQL error : cannot connect to database centreon: Access denied for user 'centreon'@'localhost' (using password: YES) (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)
2017-06-07 14:31:58 - MySQL error : cannot connect to database centreon: Access denied for user 'centreon'@'localhost' (using password: YES) (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)
2017-06-07 14:31:58 - Error when getting server properties

**Describe the results you expected:**
No error and at least the poller and default services monitored.
For example, the expected behavior is the one of the ces-standard-3.2-x86_64 iso with no updates:
![image](https://user-images.githubusercontent.com/20299744/26884092-3b2e389e-4b9f-11e7-803f-b7eaf51e38a0.png)
 

**Additional information you think important (e.g. issue happens only occasionally):**
No checks presents, may be related to #5229 

**Fixing (or trying to)**
mysql -u root
grant all on centreon.* to 'centreon'@localhost identified by 'centreon';
grant all on centreon_storage.* to 'centreon'@localhost identified by 'centreon';
reboot

-> No more error in centcore.log, but still no luck with the central polller monitoring :
![image](https://user-images.githubusercontent.com/20299744/26883919-c7c74fe4-4b9e-11e7-9d14-895788827acb.png)

**EDIT:**
New ISO :
![image](https://user-images.githubusercontent.com/20299744/26885672-9515762a-4ba3-11e7-98a5-98145c95679c.png)

Old ISO :
![image](https://user-images.githubusercontent.com/20299744/26885729-bafded04-4ba3-11e7-9ef5-dd817f0af8f1.png)

**Subsidiary question** : Does it exist a setup log?
It seems the initial database filling failed somewhere, since the checks are not even present in centreon.command (only the *-notify-by-* are present). I bet there's other data missing in this database...

FWIW, i tried 2 fresh install and another setup on virtualbox, same issue.

**EDIT 2:**
Fresh setup, 'testing' enabled, yum update, reboot, web install -> Same issue, your move :) .

**Comment by lpinsivy** [comment]
Hi,

During Centreon Web installation part, web interface generate following files with your settings:

- /etc/centreon/centreon.conf.php
- /etc/centreon/conf.pm

The problem is that the centcore process is started automatically and before that the /etc/centreon/conf.pm was created with parameters to access to database. You have to restart it.

Regards,

**Comment by imnotme** [comment]
Thanks for this reply.

However, here's the process :
- Setup centreon ISO
- Yum update
- Define php.ini timezone
- reboot
- Log web interface
- Configure
- 'Finish'
- Check centreon.conf.php -> Ok
- Check conf.pm -> Ok (the file end by '1;', i hope this is normal)
- Reboot

Then :
[root@monitoring ~]# cd /etc/init.d; for i in $(ls cent*); do service $i status; done
centcore (pid  1695) is running...
centengine status: running                                 [  OK  ]
centreontrapd is stopped

So :
[root@monitoring init.d]# cd /etc/init.d; for i in $(ls cent*); do service $i start; done
Starting centcore: cannot start centcore: centcore is alrea[FAILED]ng.
centengine start: done                                     [  OK  ]
Starting centreontrapd:                                    [  OK  ]

But :
2017-06-09 10:05:29 - MySQL error : cannot connect to database centreon: Access denied for user 'centreon'@'localhost' (using password: YES) (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)
2017-06-09 10:05:29 - Error when getting server properties

Even if the two files you pointed are correct.

Result : same issue, nothing changed.

As I said before, I have to manually grant the user on mysql. 

Before granting, the 'is running' is NO, after granting and service restart, it goes green to YES.

 - Nobody else reproduce this case?
 - Does it exist a way to log the install process?

**Comment by lpinsivy** [comment]
Yes you have previous MySQL connection error in centcore log file but this is due to first start of process without correct /etc/centreon/conf.pm file (and yes 1; at the end is ok).

Can you edit file "/etc/sysconfig/centcore" and change "error" by "debug", go to Centreon web interface in "Administration > Parameters > Debug" and check box for "Centcore Engine debug".

Then restart centcore process. I suppose everything is OK but it is old error message in log file.

Regards,

**Comment by imnotme** [comment]
You were right, after some reboots and service restart, no more error in the log.
Thanks

But :
* Maybe I fool myself, but in previous releases of centos, at least the server (localhost) was monitored by default, and some checks were presents in the configuration Command > checks menu :
![image](https://user-images.githubusercontent.com/20299744/27128496-07257566-50ff-11e7-8b5f-15572c32be99.png)

Does this behavior change in lastests releases?

**Comment by imnotme** [comment]
Okaayyyyyy for the 'no default host monitored' part, it seems centreon switche to a new model by using mandatory free plugins pack. 

Am I right? When did this changed?

**Comment by btassite** [comment]
(in CES 3.4.1 iso fresh install) The poller only got enabled for me by pressing the "Export configuration" button under Configuration, Pollers, then checking the "Move Export Files" and "Restart Monitoring Engine" boxes, selecting "Restart" (default is Reload) for Method and clicking the Export button.

`$ service cbd restart`, server reboot etc. didn't help. IIRC in CES 3.3 the init symlink was missing for the runlevel, if the poller isn't enabled on reboot this can be fixed with `$ chkconfig cbd on`, `$ service cbd start` (basically the /etc/rc.d/rc3.d/S71cbd symlink to ../init.d/cbd didn't exist).

The plugin packs aren't needed, the checks are there in /usr/lib64/nagios/plugins/ and /usr/lib/centreon/plugins/, all you need to do is define your own checks using them, or import an older configuration with clapi.

BTW, it's pretty irritating that you can't edit checks/templates from plugin packs, it's trivial to look at their config and create your own. It's a nuisance and it clutters up your config if you want slightly different things. It would be better to make the Reset button simply revert to the default if you have changed anything, with an "Are you sure?" warning.

**Comment by NicatH** [comment]
I faced up same problem. I changed /etc/centreon/centreontrapd.pm conf file.(from mode=>0 to mode=> 1).  Good Luck!
