### ISSUE TITLE
windows monitoring plugin error

### ISSUE THREAD

**Issue by elsiddh** [centreon/centreon#5626]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Hi 

We recently upgrade the centreon server from 2.0 version to 2.8 and now we got the following error message:
Unknown option: warning at /usr/lib/centreon/plugins/centreon_windows_snmp.pl line 142. 

This message appear when we try to run Windows memory monitor command is the following:
/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=10.100.XXX.XXX --snmp-version='2c' --snmp-community='amcosnmp' --warning='80' --critical='90' 

In the earlier version the plugin was working without issues

some one post the same issue on the forums:

https://forum.centreon.com/forum/plugins-aa/use-help-about-centreon-plugins-usage/147845-warning-at-centreon_windows_snmp-pl

**Centreon Web version**:  2.8.12

**Centreon Engine version**:  1.7.2

**Centreon Broker version**: 3.08

**OS**: Centos 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Xen

**Steps to reproduce the issue:**
1. Centreon 2.0
2. yum update
3. error at monitor memory on widnows Host

**Describe the results you received:**
Unknown option: warning at /usr/lib/centreon/plugins/centreon_windows_snmp.pl line 142. 

**Describe the results you expected:**
Monitor value from windows host

**Additional information you think important (e.g. issue happens only occasionally):**
This issue exist on 2.8 versions after of update

**Comment by lpinsivy** [comment]
Hi,

We updated recently the Centreon Plugin for Windows SNMP as well as the associated Plguin Pack.

Can you check that the centreon-plugin-Operatingsystems-Windows-Snmp.noarch is up to date.
Can you check also from "Configuration > Plugin packs" that the "Windows SNMP" is up to date?

Regards,

**Comment by elsiddh** [comment]
Hi,

the command yum install gives us the following output:

`[cent@local]# yum install centreon-plugin-Operatingsystems-Windows-Snmp.noarch`
`Loaded plugins: fastestmirror`
`Setting up Install Process`
`Loading mirror speeds from cached hostfile`
 `* base: mirror.tzulo.com`
 `* extras: mirror.tzulo.com`
 `* updates: repos-tx.psychz.net`
`Package centreon-plugin-Operatingsystems-Windows-Snmp-20170807-1.el6.noarch already` `installed and latest version`
`Nothing to do`

Also the plugins disappear on the webpage:

<img width="1187" alt="screen shot 2017-09-05 at 12 48 24 pm" src="https://user-images.githubusercontent.com/30730823/30074877-b7d3398c-9238-11e7-8ec8-9ba7794aa89d.png">


Thanks in advanced

**Comment by lpinsivy** [comment]
Hi,

Did you have error in /var/log/httpd/error_log or in /var/log/centreon/license-manager.log files when you access to this menu?

Can you try to clear your browser cache?

**Comment by elsiddh** [comment]
Hi 

This are the  messages that I found

error_log:
[Mon Sep 04 11:57:33 2017] [error] [client XXX.XXX.XX.XXX] PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/modules/centreon-pp-manager/core/manager/functions.php on line 0, referer: http://XXX.XXXX.XX.XXX/centreon/main.php?p=507&o=w&id=2

/var/log/centreon/license-manager.log:
2017-06-24 11:39|0|0|[RestUnauthorizedException] https://api.imp.centreon.com/api/license-manager/instance : Username or password invalid.
2017-07-13 15:41|0|0|[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance/subscription : No subscription found.
2017-07-13 15:44|0|0|[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance/subscription : No subscription found.
2017-08-10 15:34|0|0|[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance/subscription : No subscription found.
2017-08-10 15:34|0|0|[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance/subscription : No subscription found.
2017-08-11 09:16|0|0|[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance/subscription : No subscription found.
2017-08-11 11:28|0|0|[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance/subscription : No subscription found.
2017-08-29 17:36|0|0|[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance/subscription : No subscription found.
2017-08-29 17:37|0|0|[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance/subscription : No subscription found.

**Comment by lpinsivy** [comment]
What is the version of your centreon-pp-manager:

`# rpm -qa | grep centreon-pp-manager`

**Comment by stefanotoro** [comment]
Test with option:
 --warning-memory 80 --critical-memory 90

**Comment by elsiddh** [comment]
It's worked 
OK: RAM Total: 5.90GB Used: 1.83GB (31.08%) Free: 4.07GB (68.92%) | 'used'=1968504832B;0:5067505664;0:5700943872;0;6334382080

**Comment by cnpavel** [comment]
Hello,
I have the same problem with Unknown option: warning at /usr/lib/centreon/plugins/centreon windows snmp.pl line 142.

Looking on /var/log/httpd/error.log I found this:
[Fri Sep 15 15:45:44 2017] [warn] [client 10.1.1.2] incomplete redirection target of '/centreon/index.php' for URI '/' modified to 'http://10.1.0.50/centreon/index.php'
[Fri Sep 15 15:59:42 2017] [error] [client 10.1.1.2] PHP Warning:  file_put_contents(../../tmp/Update-DB-2.8.11_to_2.8.12): failed to open stream: No such file or directory in /usr/share/centreon/www/install/steps/functions.php on line 128, referer: http://10.1.0.50/centreon/install/upgrade.php
[Fri Sep 15 16:02:16 2017] [warn] [client 10.1.1.109] incomplete redirection target of '/centreon/index.php' for URI '/' modified to 'http://10.1.0.50/centreon/index.php'
[Fri Sep 15 16:11:31 2017] [notice] caught SIGTERM, shutting down
[Fri Sep 15 16:12:14 2017] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Sep 15 16:12:14 2017] [notice] Digest: generating secret for digest authentication ...
[Fri Sep 15 16:12:14 2017] [notice] Digest: done
PHP Warning:  Module 'mssql' already loaded in Unknown on line 0
[Fri Sep 15 16:12:15 2017] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 configured -- resuming normal operations
[Fri Sep 15 16:12:25 2017] [warn] [client 10.1.1.2] incomplete redirection target of '/centreon/index.php' for URI '/' modified to 'http://10.1.0.50/centreon/index.php'
[Fri Sep 15 16:14:48 2017] [error] [client 10.1.1.2] PHP Notice:  Undefined index: macroInput_#index# in /usr/share/centreon/www/class/centreonService.class.php on line 877, referer: http://10.1.0.50/centreon/main.php?p=60201&o=c&service_id=261
[Fri Sep 15 16:14:48 2017] [error] [client 10.1.1.2] PHP Notice:  Undefined index: macroInput_#index# in /usr/share/centreon/www/class/centreonService.class.php on line 877, referer: http://10.1.0.50/centreon/main.php?p=60201&o=c&service_id=261
[Fri Sep 15 16:14:48 2017] [error] [client 10.1.1.2] PHP Notice:  Undefined index: macroInput_#index# in /usr/share/centreon/www/class/centreonService.class.php on line 877, referer: http://10.1.0.50/centreon/main.php?p=60201&o=c&service_id=261
[Fri Sep 15 16:23:47 2017] [error] [client 10.1.1.2] PHP Notice:  Undefined index: macroInput_#index# in /usr/share/centreon/www/class/centreonService.class.php on line 877, referer: http://10.1.0.50/centreon/main.php?p=60201&o=c&service_id=261
[Fri Sep 15 16:23:47 2017] [error] [client 10.1.1.2] PHP Notice:  Undefined index: macroInput_#index# in /usr/share/centreon/www/class/centreonService.class.php on line 877, referer: http://10.1.0.50/centreon/main.php?p=60201&o=c&service_id=261
[Fri Sep 15 16:23:47 2017] [error] [client 10.1.1.2] PHP Notice:  Undefined index: macroInput_#index# in /usr/share/centreon/www/class/centreonService.class.php on line 877, referer: http://10.1.0.50/centreon/main.php?p=60201&o=c&service_id=261
[Fri Sep 15 16:24:18 2017] [error] [client 10.1.1.2] PHP Notice:  Undefined index: macroInput_#index# in /usr/share/centreon/www/class/centreonService.class.php on line 877, referer: http://10.1.0.50/centreon/main.php?p=60201&o=c&service_id=261
[Fri Sep 15 16:24:18 2017] [error] [client 10.1.1.2] PHP Notice:  Undefined index: macroInput_#index# in /usr/share/centreon/www/class/centreonService.class.php on line 877, referer: http://10.1.0.50/centreon/main.php?p=60201&o=c&service_id=261
[Fri Sep 15 16:24:18 2017] [error] [client 10.1.1.2] PHP Notice:  Undefined index: macroInput_#index# in /usr/share/centreon/www/class/centreonService.class.php on line 877, referer: http://10.1.0.50/centreon/main.php?p=60201&o=c&service_id=261
[Fri Sep 15 17:39:49 2017] [error] [client 10.1.1.2] PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/modules/centreon-pp-manager/core/manager/functions.php on line 0, referer: http://10.1.0.50/centreon/main.php?p=103
[Fri Sep 15 17:44:39 2017] [error] [client 10.1.1.2] PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/modules/centreon-pp-manager/core/manager/functions.php on line 0, referer: http://10.1.0.50/centreon/main.php?p=60201&o=c&service_id=274
[Fri Sep 15 17:44:42 2017] [error] [client 10.1.1.2] PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/modules/centreon-pp-manager/core/manager/functions.php on line 0, referer: http://10.1.0.50/centreon/main.php?p=650
[Fri Sep 15 17:46:58 2017] [error] [client 10.1.1.2] PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/modules/centreon-pp-manager/core/manager/functions.php on line 0, referer: http://10.1.0.50/centreon/main.php?p=60902&poller=1

How can I reinitiate the install process so that the DB will be updated acordingly?

**Comment by cnpavel** [comment]
Updating from 2.8.12 to 2.8.13 solved the problem.
Thanks!
