### ISSUE TITLE
[2.8.12] Services' Comments not well managed

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#5630]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.12

**Centreon Engine version**:  1.7.2

**Centreon Broker version**:  3.0.8

**OS**:  CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical

**Steps to reproduce the issue:**
1. Acknowledge a non-ok service, add a comment "comment 1"
2. Enter in the service's detail page, click on "Add a comment for this service", add a comment "comment 2 detail"
3. Go in "Monitoring  >  Downtimes  >  Comments", delete "comment 1"
4. Go in "Monitoring  >  Status Details  >  Services", put you mouse on the Acknowledge's icon, you will still see "comment 1" ! But **not** "comment 2 detail"
5. Return in the service's detail page, scroll down until you see " All Comments for this service". You will only see "comment 2 detail"

**Describe the results you received:**
The 1rs comment is erased from both  "Monitoring  >  Downtimes  >  Comments", and the service's detail page. But NOT from the monitoring view. The 2nd comment, is never shown on mouse-over on the Acknowledge's icon.

**Describe the results you expected:**
I would like to be able to add another comment on an Acknowledge, and this comment must be visible "on mouse-over" the Ack's icon.
If i delete a comment, this comment must be remove everywhere for consistency.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

It is not a bug because the first comment is not a real comment but the comment of a acknowledgement.

So when you go to "Monitoring > Downtimes > Comments" to delete the comment, you just remove the flag "comment" of the comment associated to the acknowledgement but it still linked to the acknowledgement itself.

So you can't see anymore as a comment but in the "Monitoring > Status Details > Services" you will always see it because you see the description of the acknowledgement.

Regards,
