### ISSUE TITLE
[Command line] - Execute 2 shell command separated but semi-colon or &&

### ISSUE THREAD

**Issue by troptop** [centreon/centreon#5966]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.7
**Centreon Engine version**: 
3.4
**Centreon Broker version**: 

**OS**: 
Centos
**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Steps to reproduce the issue:**
1. Got to "command" page to add a new page.
2. add the command line : 
var=$(cat /my/file) && $USER2$/check_http -S $HOSTADDRESS$ -P $var
or 
var=$(cat /my/file) ; $USER2$/check_http -S $HOSTADDRESS$ -P $var

**Describe the results you received:**
the plugin do not have output 

**Describe the results you expected:**
HTTP OK 200 lucky you

**Additional information you think important (e.g. issue happens only occasionally):**
I would like to know if it is possible to execute 2 commands in the command line field?
I would like to be able to put the content of a file in a variable?

How can I do that?

**Comment by bouda1** [comment]
Hi,

There is a possible conflict between shell variables and Centreon macros, in your code, we have :
'var=$(cat /my/file) && $USER2$/check_http -S $HOSTADDRESS$ -P $va'

And centreon macros are text between two '$', so our parser is looking for a macro called `$(cat /my/file) && $` and another one called `$/check_http -S $`. Since it does not find their value, it replaces them by nothing ; and now I think you see why centreon cannot execute your code like this.

In a near future, we could fix the parser to verify that the text between '$' looks like a variable but now if you want a fix, I propose that you make a full script doing what you want and you just have to call it from the UI.

Regards.

**Comment by troptop** [comment]
Thank you very much for your quick answer.
