### ISSUE TITLE
[Plugin Manager] Object not installed: autodiscovery

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon#7131]
Hey guys,

I hope it's the right place where to put my issue. I have a fresh installation of Centreon 18.10 from the ISO file and haven't done any update yet. I tried to install the available plugins and there is always a message popping up:
![grafik](https://user-images.githubusercontent.com/35097389/51243960-27770600-1984-11e9-8b0e-35a2010c4070.png)
This is the message when I try to install the Plugin Pack "Linux SNMP" or "Cisco standard".
![grafik](https://user-images.githubusercontent.com/35097389/51244063-6f962880-1984-11e9-8879-370787336ed3.png)

Does anyone have the same issue?

Best regards, Michael

**Comment by lpinsivy** [comment]
Dear,

We recently update the [Plugin Pack Manager documentation](https://documentation.centreon.com/docs/plugins-packs/en/latest/installation.html#pack-installation) to explain this message.

It means that an additional configuration contained in the pack has not been installed. That's why the icon of the pack is in orange color and not green.

Don't worry, it is only additional configuration and you can deploy your monitoring of Cisco equipment.

It concerns a configuration for the Centreon Auto Discovery module available in the Centreon IMP offer.

Thank you for your feedback and we plan to improve this message in few weeks.

Regards,

**Comment by MikeW83** [comment]
So i can ignore this message? Maybe you can fix it in any way. It's a little bit confusing when someone like me don't use Centreon IMP. ;-)

**Comment by bouhaines** [comment]
bonjour
je suis débutante et je suis entrain de faire mon stage ou je doit mettre en place centreon 10.18. je l'ai installé et j'ai crée des hotes et des services et j'ai fait la configuration mais le problème dans supervision je vois rien et il m'affiche que la mise a jour de la base de donnée n'est activé, donc c'est pour cela je vois rien dans la supervision? et comment je peux activer la mise  a jour de la base de donnée ?
merci
