### ISSUE TITLE
[Graphs] Graph for incoming traffic missing

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon#7135]
Hey guys,

a new question: Why is the traffic_in not displayed? I have a completly new installation and have never used graphs before. Do I have anything done wrong?

![grafik](https://user-images.githubusercontent.com/35097389/51251625-0caf8c00-199a-11e9-84bc-161ba2c092da.png)

And here you can see, that I receive data for traffic_in:
![grafik](https://user-images.githubusercontent.com/35097389/51251722-3963a380-199a-11e9-9e92-ada5d44852a0.png)

What setting is wrong here? When i split the graph there I can also see the negative values, but Y-axis is not converted to the negative value. So no filled line is displayed.
Thank you very much.

EDIT: I have checked the settings with the demo system. It seems to be the same. Or do I have anything not considered?

Best regards, Michael

**Comment by kozfelipe** [comment]
@MikeW83 

go to Monitoring  >  Performances  >  Curves
select Traffic_In and uncheck the Invert field

**Comment by Sims24** [comment]
Hi @MikeW83 

If you want to see the in and the out like this : 

![image](https://user-images.githubusercontent.com/12429463/51386629-68f1e780-1b23-11e9-8b6b-26d9ce8e4860.png)

Please prefer to set the "Traffic" graph template in your service extended information (and reload centreon-engine) rather than the solution proposed by @kozfelipe .

**Comment by MikeW83** [comment]
Thank you, everything is working now.
