### ISSUE TITLE
httpd / rh-php71 / php5.4.16 settings problems

### ISSUE THREAD

**Issue by gabyfulchic** [centreon/centreon#7178]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10

**Centreon Engine version**: 18.10

**Centreon Broker version**: 18.10

**OS**: Centos7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OVH vps

**Steps to reproduce the issue:**
1. Upgrade centreon 2.8.26 to 18.10
2. Try to upgrade after cmds in the web nav, getting an 500 error
3. So install php71 manually because it was needed
4. now When i go to the web page the php is not interpreted

i think a problem in php/httpd conf but idk why i need to modifiy something like this.

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/22600727/52343407-45320b00-2a18-11e9-8cb2-34f9b3968174.png)

![image](https://user-images.githubusercontent.com/22600727/52343342-19168a00-2a18-11e9-81de-fd4dd4b733eb.png)

**Additional information you think important (e.g. issue happens only occasionally):**

-> i tried to upgrade but nothing was working because i was needing a new php-version. (in the tuto upgrade to 18.10 there is nothing wrote about installing rh-php71).
-> so installed it : yum install rh-php71 rh-php71-*
-> i've got the fpm one working and active but when i type php -v i see php5.4.16.....

Warmly gabyfulchic

**Comment by adr-mo** [comment]
Hi @gabyfulchic,

Thanks for the feedback :)
Did you follow step by step the documentation provided here ? https://documentation.centreon.com/docs/centreon/en/latest/upgrade/from_packages.html#centreon-central-server-upgrade

Normally when installing the RedHat Software Collections and the new rpm release of Centreon, you should get the php71 installed (though yum dependency system).

Regards

**Comment by gabyfulchic** [comment]
Hi @adr-mo 

Yeah i followed that one.

I tried it again, 
![image](https://user-images.githubusercontent.com/22600727/52344673-ac9d8a00-2a1b-11e9-9491-2a9bdbc1fd8d.png)

But i still got the error.

Do you think that php and rh-php can't live together on a system ?

warmly gabyfulchic

**Comment by adr-mo** [comment]
The answer is yes :)

The php cli still uses the php 5.4.16 version of it that is why you get this version.

To get through this issue you can run `scl enable rh-php71 bash` and then try `php -v`

For the other issue, sounds familiar...

I'll invite you to join the Slack community, other community members might experienced your issue. https://centreon.github.io/register-slack

**Comment by gabyfulchic** [comment]
Now i've got php -v sending me 7.1.8 but i've always got the pages not interpreted.
I've got that result when i try in cli :
![image](https://user-images.githubusercontent.com/22600727/52346700-79a9c500-2a20-11e9-8967-a84583fb6fd5.png)

Maybe need i to explain at httpd where the good binary for the new php is.
now it's : "/opt/rh/rh-php71/root/usr/bin/php"
But when i type which it works :/
![image](https://user-images.githubusercontent.com/22600727/52347005-369c2180-2a21-11e9-958e-741ef0139d61.png)

Ok ty i'll post something if i keep having the issue :/

**Comment by gabyfulchic** [comment]
I don't really understand the following indication xD :
![image](https://user-images.githubusercontent.com/22600727/52349067-06a34d00-2a26-11e9-8e51-e26b9eb5973f.png)

**Comment by gabyfulchic** [comment]
Ok i've maybe found the problem, i'll do some tests etc but take a look :
![image](https://user-images.githubusercontent.com/22600727/52356056-d5317e00-2a33-11e9-80e8-8c56b7482b01.png)

I don't have any php.conf in my httpd and my 10-centreon.conf is like :
![image](https://user-images.githubusercontent.com/22600727/52356314-440ed700-2a34-11e9-9e55-6fbac4319d52.png)

I have a 10-centreon.conf.rpmnew like the one add by the fresh install of a new centreon server.

So i'll try some things.

Warmly gabyfulchic :)

**Comment by adr-mo** [comment]
Okay do not hesitate @gabyfulchic to close the issue if you found the solution :)
Otherwise we still available to try helping you :)

Regards,

**Comment by BlackstormFirst** [comment]
Hello,
I had the same problem when i've investigated the "partitionning" script issue...

I am using the latest CES OVF from the official web site and the VM has been fully patched.

The Centreon pluging check for database partitionning was down since i started the product, so, after some investigation i found 2 errors.

The first one is directly linked to this post, apparently "Classes" are not correctly interpreted by php 5.4, the 5.4 come with the OVF.

Like you said, a yum upgrade don't update the php to the 7.1 release... my "php -v" is still on 5.4, but oddly the php7.1-fpm is correctly installed...

So i decide to install the php5.5 packages (all packages already installed with 5.4).

After running the correct release on the "centreon-partitioning.php" script, there was a last issue from the file "partEngine.class.php" (line 168 and 248) where the functions end with a class type. When you remove the end of the declaration, the script runs again.


Please, can you provide us a new OVF/OVA image on the web site please ? It appear the latest ISO release have no error when i tried it last week... but i don't check the php version.

What release of php should i use with the latest centreon website please ? 5.5 ? 7.1 ? 7.2 ?
Thanks in advance.
Best Regards,

**Comment by adr-mo** [comment]
Hello @BlackstormFirst,

Thanks for the feedback !

I'll check with the release manager to get a new version of the OVA/OVF files.

To answer your question, the latest version of Centreon works with **PHP 7.1/7.2.**

You can find those information in our documentation https://documentation.centreon.com/docs/centreon/en/latest/installation/prerequisites.html#dependent-software

Regards,

**Comment by BlackstormFirst** [comment]
@adr-mo,
Hello, and thanks for the answer ^^

I will check my env. to be fully up-to-date.

I addition, and just for feedback, i can say 2 more things: 
- On the OVF, the VMware CLI is still on version 5.5, so you cannot use it to fully manage ESXi 6.5 or 6.7, and when you try to upgrade it, with the latest offical release sources (6.5U1 -> build 7397310), you must uninstall some centreon packages before, because they are fully dependant to the centreon vmware CLI plugins (so i remove them, to support my esxi, and i use another nagios plugin to do the job on my ESXi).

- On the latest ISO release (centreon-18.10-5.el7.x86_64), after the installation (CentOS, Fully patched, Centreon install), i don't have any "Centreon-Central" default host into the web page... so i had to import this host with CLAPI from another Centreon web site.

Best Regards,

**Comment by adr-mo** [comment]
@BlackstormFirst Thanks for the feedback :)
I'll let the Product Manager know about this and we'll discuss to get it right for the next releases :)

**Comment by BlackstormFirst** [comment]
Thanks^^

I just find another thing ^^

With the ISO release, i don't see, into the centreon user crontab, the command to auto update the partition tables, probably another forgets ^^

I found the first connect shell script (into the ovf release) very usefull to check prerequisite needs, please, can you provide it with others release ? (sources and iso files).

Thanks a lot ^^

**Comment by lpinsivy** [comment]
@BlackstormFirst thank you for your feedback.

In the ISO we can't make a link on php to PHP7.1 binary because this doesn't respect CentOS/RedHat policy.

Regards,
