### ISSUE TITLE
18.10.4: cannot set downtimes

### ISSUE THREAD

**Issue by elmarsievers** [centreon/centreon#7373]
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

***Versions (rollback to working version) ***
centreon-database-18.10.2-3.el7.centos.noarch
centreon-18.10.2-3.el7.centos.noarch
centreon-widget-host-monitoring-18.10.0-11.el7.centos.noarch
centreon-clib-18.10.0-2.el7.centos.x86_64
centreon-broker-cbmod-18.10.1-1.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Database-20190111-102147.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190111-102147.el7.centos.noarch
centreon-connector-perl-18.10.0-2.el7.centos.x86_64
centreon-engine-18.10.0-4.el7.centos.x86_64
centreon-widget-live-top10-memory-usage-18.10.0-6.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-18.10.0-6.el7.centos.noarch
centreon-release-18.10-2.el7.centos.noarch
centreon-license-manager-18.10.1-2.el7.centos.noarch
centreon-pp-manager-18.10.2-1.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20190111-102147.el7.centos.noarch
centreon-connector-18.10.0-2.el7.centos.x86_64
centreon-engine-extcommands-18.10.0-4.el7.centos.x86_64
centreon-widget-servicegroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-widget-graph-monitoring-18.10.0-6.el7.centos.noarch
centreon-license-manager-common-18.10.1-2.el7.centos.noarch
centreon-broker-core-18.10.1-1.el7.centos.x86_64
centreon-plugin-Network-Cisco-Standard-Snmp-20190111-102147.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190111-102147.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190111-102147.el7.centos.noarch
centreon-poller-centreon-engine-18.10.2-3.el7.centos.noarch
centreon-web-18.10.2-3.el7.centos.noarch
centreon-common-18.10.2-3.el7.centos.noarch
centreon-engine-daemon-18.10.0-4.el7.centos.x86_64
centreon-widget-hostgroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-widget-service-monitoring-18.10.0-11.el7.centos.noarch
centreon-connector-ssh-18.10.0-2.el7.centos.x86_64
centreon-broker-18.10.1-1.el7.centos.x86_64
centreon-broker-cbd-18.10.1-1.el7.centos.x86_64
centreon-plugin-Applications-Databases-Mysql-20190111-102147.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190111-102147.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190111-102147.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190111-102147.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190111-102147.el7.centos.noarch
centreon-trap-18.10.2-3.el7.centos.noarch
centreon-perl-libs-18.10.2-3.el7.centos.noarch
centreon-widget-grid-map-18.10.0-6.el7.centos.noarch
centreon-widget-engine-status-18.10.0-9.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190111-102147.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190111-102147.el7.centos.noarch
centreon-base-config-centreon-engine-18.10.2-3.el7.centos.noarch
centreon-widget-tactical-overview-18.10.0-6.el7.centos.noarch
centreon-broker-storage-18.10.1-1.el7.centos.x86_64
centreon-plugin-Operatingsystems-Windows-Snmp-20190111-102147.el7.centos.noarch

***Operating System***

CentOS 8

***Additional environment details (AWS, VirtualBox, physical, etc.):***
virtual vmware

<h3> Description </h3>

If I want to set downtimes directly in service status page centreon/main.php?p=20201 it does nothing after selecting a time.

**Comment by adr-mo** [comment]
Hi @elmarsievers,

Thanks for the feedback :100: 

First of all could you please check several things in the logs.
When doing the action could you check that nothing specials are in the following logs

- `tailf /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log` (_php logs_)
- `tailf /var/log/centreon/centcore.log` (_centcore logs_)
- Could you also check for errors in the developers console of the browser ? (F12 on Google Chrome)

Thanks

Regards,

**Comment by bldrdash** [comment]
@elmarsievers 

I had the same issue after upgrading.  It looks like they've made some changes to the systemd config files which broke my install on CentOS 7.

Check the following (don't know what's changed in Cent8, so there could be some differences):

- ps aux | grep centcore (It's wasn't running on my system)
- systemctl is-enabled centcore (was disabled)
- systemctl enable centcore
- systemctl start centcore
- systemctl status centcore (should be running at this point)

If it's running after enabling and starting, you may see some messages related to executable permissions on the systemd config files.  You can fix by: 
- cd /usr/lib/systemd/system
- chmod 644 cent* cbd.service

This can get you going; however, it won't start on reboot due to a lack of dependency on MySQL/MariaDB.  I haven't taken the time to understand how the systemd files are *supposed* to work in 18.10.4 and resolve the dependency.  But it will work if you manually start centcore after reboot.

I'm going to check out 19.X first before investing time in resolving 18.X issues.

**Comment by elmarsievers** [comment]
@bldrdash

Thank you. centcore was the Problem. In 19.04.0 there is no Problem anymore with no started centcore after reboot.

Kind Regards
