### ISSUE TITLE
Centreon 19.04 - Failed to duplicate host

### ISSUE THREAD

**Issue by oragain** [centreon/centreon#7495]
<h1>BUG REPORT INFORMATION </h1>
Failure tu duplicate hosts

<h3> Prerequisites </h3>
Central-Web
***Versions***
19.04

For the RPM based systems

<h3> Description </h3>

Unable to duplicate host.
Upon failure and reloading of the page, a duplicate host does appear in the list
Opening it shows all information as blank and saving does nothing

<h3> Steps to Reproduce </h3>
Duplicate hosts a couple of times and then you can't duplicate anymore

<h3> Describe the received result </h3>
Blank page without error messages

<h3> Describe the expected result </h3>
Error messages + self healing

<h3> Additional relevant information (e.g. frequency, ...) </h3>

Running the query in the MariaDB engine:

MariaDB [centreon]> INSERT INTO hostgroup_relation
    ->                                     VALUES ('', '2', '4');
ERROR 1366 (22007): Incorrect integer value: '' for column `centreon`.`hostgroup_relation`.`hgr_id` at row 1

**Comment by adr-mo** [comment]
Hi @oragain,

Thanks for the feedback :100:

As discussed on **Slack** could you please try to retry the add command action and lookup for errors in
- `/var/opt/rh/rh-php71/log/php-fpm/centreon-error.log`
- `/var/log/centreon/sql-error.log`

Thanks.

Regards,

**Comment by adr-mo** [comment]
Hi @oragain 

As discussed on **Slack** the issue was linked to the fact that SQL strict mode was enabled on the SQL monitoring server.

Although, Centreon is **not** compatible yet with this SQL mode.

A PR https://github.com/centreon/centreon/pull/7496 has been created to let users informed of this restriction.

Closing the ticket.

Regards,
