### ISSUE TITLE
Servel strange issues when I migrate the centreon from old to 19.04

### ISSUE THREAD

**Issue by JohnTianGuo** [centreon/centreon#7499]
First issue:
----
When Upgrade the web interface the menu “Performance->Graphic’ changed ‘Syslog->Graphic’ and the graphic details disappeared ,how strange it is as follow:
![1](https://user-images.githubusercontent.com/48991627/56874566-48fc8900-6a6d-11e9-8c80-033b2b4caf74.png)

when i check the issus ,i found this menu path as follow ->Administration  >  Parameters  >  RRDTool  the RRDTool's details disappeared either:
![2](https://user-images.githubusercontent.com/48991627/56874605-89f49d80-6a6d-11e9-8f3e-2e050bf39b1a.png)

Second issue:

i check the command in central centreon ,after run the  command ,there was ouput ,but no output in web pages , as the follow:

# 
![3](https://user-images.githubusercontent.com/48991627/56874638-e1930900-6a6d-11e9-9747-492828ea0281.png)
![4](https://user-images.githubusercontent.com/48991627/56874657-038c8b80-6a6e-11e9-8df0-9dd47a8b32af.png)

as the pollor had the same question too 

Third issue:

at the poller server ,i install the Config::IniFiles, but the service still give the hint:

Could not load the Perl module 'Config::IniFiles' Can't locate Config/IniFiles.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 13) line 1.

in fact  I run the command in the poller , there was output 

Fourth issue：
In fact i upgrade the web ,the Sql run normally but the centreon-partitioning give error message.  and then i partition the tables manually .

Five issue:
when i  restart the mysqld cbd , i run the command  

ss -ntulp | grep cbd 

only found the port 5669 and 5670 but cbd not connected the  mysqld port 3306 , the RRDTool not connected the mysql port either ,as follow:

![image](https://user-images.githubusercontent.com/48991627/56874796-e6a48800-6a6e-11e9-8c4b-056c58113f73.png)

the migration i felt there are many unknown bugs in the process while i try to migrate about one month ,always disturbed the last step .how strange .

The centreon support made me crazy .

in the world ,many more IT company , i operated many more software and debug all the error .the first debuging the centreon and met some stange issue.

by the way ,i promised that , i operated the migration according the documents from centreon official pages.

thanks in advance

**Comment by adr-mo** [comment]
Hi @JohnTianGuo 

First of all I wanted to let you know that there is an issue template [ISSUE_TEMPLATE.md](https://github.com/centreon/centreon/blob/master/.github/ISSUE_TEMPLATE.md) that should be used for **BUG REPORT**.

It is not here for nothing it allows us **Centreon** to get as much as possible information to diagnostic your problems.

For example **"FROM OLD"** what do you mean by that ? 18.10.x ? 2.8.x ? ....

**ISSUE 1**

- Are you admin of the Central Server ?
- Are you an user with ACL ?
- Did you tried to **clean the web browser cache** ?

For the second part of your issue. It is **NOT** a bug the fact that those RRD options were removed.

It is mentionned in the [release note](https://github.com/centreon/centreon/releases) that should have read.

> [Install] remove obsolete rrdtool configuration and sources (PR/#7195)

Here is a part of the [SQL upgrade](https://github.com/centreon/centreon/blob/master/www/install/sql/centreon/Update-DB-19.04.0.sql) to prove it.

```
-- Remove unused options
DELETE FROM options WHERE options.key IN ('rrdtool_title_font', 'rrdtool_title_fontsize', 'rrdtool_unit_font', 'rrdtool_unit_fontsize', 'rrdtool_axis_font', 'rrdtool_axis_fontsize', 'rrdtool_watermark_font', 'rrdtool_watermark_fontsize', 'rrdtool_legend_font', 'rrdtool_legend_fontsize');
```
**ISSUE 2**

As far as I can see from your screenshot, the command output **is not formatted** in a way that centreon can understand it. It is quite normal that nothing appears in the Centreon Web inferface.

Is this plugin coming from one of the **Official Plugin Pack** provided by Centreon ?
If not, installing, configuring custom checks is on your hand.

**ISSUE 3**

In what world is this related to **Centreon** ? I just Googled your issue and found the solution.
Please feel free to do the **same**.

**ISSUE 4**

> In fact i upgrade the web ,the Sql run normally but the centreon-partitioning give error message. and then i partition the tables manually .

What error ? Could you provide more information ? Like **logs** ? (the kind of things asked by the ISSUE_TEMPLATE :+1: )

**ISSUE 5**

Again no information provided so we can't find a solution for you.
- Are all the outputs of broker correctly **defined** ?
- Are all the broker processes correctly **started** ?

**Finally just for the record.**

> The centreon support made me crazy .

You can't say that Centreon Support Team drove you crazy because you have not subscribed for support. I want also to invite you to read this https://github.com/centreon/centreon/blob/master/CODE_OF_CONDUCT.md and let you informed that this will be the last warning before a **definitive ban of our community.**

Feel free to seek for help on our official Slack channel if you are not willing to subscribe to support.

**GitHub** is meant to open **real** issues (_code related_), to ask for new features but it is **NOT** meant to be support.

Regards,

**Comment by JohnTianGuo** [comment]
> Hi @JohnTianGuo
> 
> First of all I wanted to let you know that there is an issue template [ISSUE_TEMPLATE.md](https://github.com/centreon/centreon/blob/master/.github/ISSUE_TEMPLATE.md) that should be used for **BUG REPORT**.
> 
> It is not here for nothing it allows us **Centreon** to get as much as possible information to diagnostic your problems.
> 
> For example **"FROM OLD"** what do you mean by that ? 18.10.x ? 2.8.x ? ....
> 
> **ISSUE 1**
> 
> * Are you admin of the Central Server ?
> * Are you an user with ACL ?
> * Did you tried to **clean the web browser cache** ?
> 
> For the second part of your issue. It is **NOT** a bug the fact that those RRD options were removed.
> 
> It is mentionned in the [release note](https://github.com/centreon/centreon/releases) that should have read.
> 
> > [Install] remove obsolete rrdtool configuration and sources (PR/#7195)
> 
> Here is a part of the [SQL upgrade](https://github.com/centreon/centreon/blob/master/www/install/sql/centreon/Update-DB-19.04.0.sql) to prove it.
> 
> ```
> -- Remove unused options
> DELETE FROM options WHERE options.key IN ('rrdtool_title_font', 'rrdtool_title_fontsize', 'rrdtool_unit_font', 'rrdtool_unit_fontsize', 'rrdtool_axis_font', 'rrdtool_axis_fontsize', 'rrdtool_watermark_font', 'rrdtool_watermark_fontsize', 'rrdtool_legend_font', 'rrdtool_legend_fontsize');
> ```
> **ISSUE 2**
> 
> As far as I can see from your screenshot, the command output **is not formatted** in a way that centreon can understand it. It is quite normal that nothing appears in the Centreon Web inferface.
> 
> Is this plugin coming from one of the **Official Plugin Pack** provided by Centreon ?
> If not, installing, configuring custom checks is on your hand.
> 
> **ISSUE 3**
> 
> In what world is this related to **Centreon** ? I just Googled your issue and found the solution.
> Please feel free to do the **same**.
> 
> **ISSUE 4**
> 
> > In fact i upgrade the web ,the Sql run normally but the centreon-partitioning give error message. and then i partition the tables manually .
> 
> What error ? Could you provide more information ? Like **logs** ? (the kind of things asked by the ISSUE_TEMPLATE  )
> 
> **ISSUE 5**
> 
> Again no information provided so we can't find a solution for you.
> 
> * Are all the outputs of broker correctly **defined** ?
> * Are all the broker processes correctly **started** ?
> 
> **Finally just for the record.**
> 
> > The centreon support made me crazy .
> 
> You can't say that Centreon Support Team drove you crazy because you have not subscribed for support. I want also to invite you to read this https://github.com/centreon/centreon/blob/master/CODE_OF_CONDUCT.md and let you informed that this will be the last warning before a **definitive ban of our community.**
> 
> Feel free to seek for help on our official Slack channel if you are not willing to subscribe to support.
> 
> **GitHub** is meant to open **real** issues (_code related_), to ask for new features but it is **NOT** meant to be support.
> 
> Regards,

thank you again , i closed the issue 
i give up the migration 
fuck , waste my on whole month to operate this shit software i met

**Comment by adr-mo** [comment]
Hi @JohnTianGuo 

Hope that you'll find a solution more suitable to your **abilities**.

We're sorry that you feel that way.

Regards,
