### ISSUE TITLE
Upgrade from 18.10.5 to 19.04.2

### ISSUE THREAD

**Issue by wackou72** [centreon/centreon#7647]
Hi,

I attempted to upgrade Centreon 18.10.5 to 19.04.2.

I followed https://documentation-fr.centreon.com/docs/centreon/fr/19.04/upgrade/from_packages_1810.html#mise-a-jour-du-serveur-centreon-central and it fails here :

![59095704-70226200-8919-11e9-9ef6-c179b89a3382](https://user-images.githubusercontent.com/21340779/60019377-01b9ff80-968e-11e9-9aa1-ad6cefb80c0b.png)

I've followed this https://github.com/centreon/centreon/issues/7596

Commenting the 4 lines in /usr/share/centreon/www/install/sql/centreon/Update-DB-19.04.1.sql and upgrade process terminaned.

Is these line important ? How can I be sure that everything is working.

Thanks.

**Comment by adr-mo** [comment]
Hi @wackou72

Thanks for the feedback :100: 

If you want to make sure that the upgrade has been correctly done you can check that the following columns are defined in `centreon` database
- http_method
- http_port
- no_check_certificate
- no_proxy

Here is the command to check it

`mysql centreon <<< "DESC remote_servers;" | grep -E "(http_method|http_port|no_check_certificate|no_proxy)"` (use your DB credentials)

Let me know if those are correctly defined and I'll close the ticket since the next release to come will correct this issue.

Regards

**Comment by wackou72** [comment]
It seems to work.
Here are the following output :
`http_method           enum('http','https')  NO     http  
http_port             int(11)               YES    NULL  
no_check_certificate  enum('0','1')         NO     0     
no_proxy              enum('0','1')         NO     0    `

Thank you so much

**Comment by adr-mo** [comment]
Awesome :+1:
