### ISSUE TITLE
Si les traps SNMP ne sont pas définies dans Centreon et si elles ne sont pas rattaché à un service passif de l'hôte, alors elle ne sont pas traitées.

### ISSUE THREAD

**Issue by KablanHenock** [centreon/centreon#7717]
Si les traps SNMP ne sont pas définies dans Centreon et si elles ne sont pas rattaché à un service passif de l'hôte, alors elle ne sont pas traitées.

https://documentation-fr.centreon.com/docs/centreon/en/2.8.x/administration_guide/02k.html?highlight=trap#faq

_Originally posted by @lpinsivy in https://github.com/centreon/centreon/issues/5979#issuecomment-356622662_

**Comment by KablanHenock** [comment]
> 
> 
> Si les traps SNMP ne sont pas définies dans Centreon et si elles ne sont pas rattaché à un service passif de l'hôte, alors elle ne sont pas traitées.
> 
> https://documentation-fr.centreon.com/docs/centreon/en/2.8.x/administration_guide/02k.html?highlight=trap#faq
> 
> _Originally posted by @lpinsivy in [#5979 (comment)](https://github.com/centreon/centreon/issues/5979#issuecomment-356622662)_
Et si tout est bien fait comme tu le suggère et que les traps restent dans le /var/spool/centreontrap/ mais qu'on n'observe pas toujours d'alarme? Parce que moi c'est mon cas

**Comment by lpinsivy** [comment]
Hi @KablanHenock what is your need?

**Comment by KablanHenock** [comment]
Hello ! I need Support to know how to allow alarm to appear on centreon when i generate a trap from a VM to my poller

**Comment by KablanHenock** [comment]
For the moment all trap that I already generate are in /var/spool /centreontrapd/ but nothing appear on centreon

**Comment by M4rotte** [comment]
One could imagine a kind of tray which presents untreated traps (yes that’s normal they’re untreated if there is no passive services associated with them…). It could also presents them nicely (how hard a raw trap hard is to read for a humain…). It could also warn about the fact their untreated and propose the user to configure centreon(trapd) properly… Another use would be that the operator could confirm to the trap sender that its trap is arrived well (and so the problem is centreon’s size).

**Comment by KablanHenock** [comment]
OK but i don't understand why, because there is a passive service associate with (link-up). But nothing. If you want let me share with you my configuration

**Comment by KablanHenock** [comment]
O can speek also in french if you prefere

**Comment by tanguyvda** [comment]
Hello, 

if all your traps are in /var/spool/centreontrapd, it is because centreontrapd is not running. 

make sure you have the following /etc/centreon/centreontrapd.pm file on your central server 

#############################################
# File Added by Centreon
#
our %centreontrapd_config = (
    # Temps en secondes avant d'arrêter brutalement les sous processus
    timeout_end => 30,
    spool_directory => "/var/spool/centreontrapd/",
    # 0 = central, 1 = poller
    mode => 0,
    cmd_timeout => 10,
    centreon_user => "centreon",
);

1;




make sure you have the following /etc/centreon/centreontrapd.pm file on your poller:

#############################################
# File Added by Centreon
#
our %centreontrapd_config = (
        # databases credentials
        centreon_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        centstorage_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        db_type => 'SQLite',
        # server type (0: central, 1: poller)
        mode => 1
);

1;

and restart the centreontrapd daemon (service centreontrapd restart)

you can check that it is running with the following command : 
ps aux | grep -i centreontrapd 

I strongly advise to people to use the debug mode of centreontrapd when it is the first time they are trying to receive traps. 

to do so : head over your centreon web interface and in administration -> parameters -> debug
tick the Centreontrapd debug checkbox. 

to make sure everything is in debug mode, open the /etc/sysconfig/centreontrapd file (on your poller and/or central depending on which server is going to receive your traps). When done, execute the following command : 

systemctl daemon-reload
service centreontrapd restart

to make sure everything is in debug, you should have something like that in the /var/log/centreon/centreontrapd.log file

019-08-30 16:17:41 - DEBUG - 30407 - PID: 30407
2019-08-30 16:17:41 - ERROR - 30407 - Mode: central server
2019-08-30 16:17:41 - DEBUG - 30407 - Sleeping for 2 seconds
2019-08-30 16:17:43 - DEBUG - 30407 - Sleeping for 2 seconds
2019-08-30 16:17:45 - DEBUG - 30407 - Sleeping for 2 seconds
2019-08-30 16:17:47 - DEBUG - 30407 - Sleeping for 2 seconds

(don't mind the "mode: central server", it's because i've used a central server to show you the logfile)

as soon as you'll receive a trap, it will tell you a lot of information regarding what centreontrapd is doing (either throwing the trap in the bin because there's no host/service associated or no known OID and so on)


and don't forget that when you're working with traps, you have to export your configuration as always, but you also need to export the snmp traps configuration on your poller (SNMP traps -> generate menu in your web interface)
