### ISSUE TITLE
[Stream Connector] recurrent downtime events

### ISSUE THREAD

**Issue by ppremont-capensis** [centreon/centreon#9086]
### Feature explanation

Add a broker event when you define a recurrent downtime event.

### What is the value of the wanted feature ?

Today (if I'm not wrong), no events are sent when you define a recurrent downtime.
So you need to wait for the start of the downtime to catch a part of this downtime.
To synchronize this information with other tools, it should be good to have a "reccurent downtime event" with all the informations carried by  this event.

### Additional information

Centreon broker version tested : centreon-broker-20.04.8-1.el7.centos.x86_64

**Comment by lpinsivy** [comment]
Hi @ppremont-capensis, what do you means about "To synchronize this information with other tools". What is your need?

Regards,

**Comment by Sims24** [comment]
Hi @ppremont-capensis ,

As of today, the recurrent downtime is just an Centreon concept. 

Centreon schedules recurrent downtimes thanks to a cronjob but behind the scene, it's still a simple downtime like any other one in the engine. 

You may want to rather use the API v1 providing endpoint to list all the downtimes including recurrent and poll this endpoint to update the list within Canopsis. 

In the future, if we choose to make Recurrent Downtimes an Engine object rather than a Centreon concept, it will be possible but kind of big change ;) 

Thanks
