### ISSUE TITLE
upgrade to 20.10.2 and no email sending

### ISSUE THREAD

**Issue by Mickael06** [centreon/centreon#9455]
Since upgrade to 20.10.2 (centos 7) mails notification are not sending.
In event logs, I see service-notify-by-email generated but email are not sending anymore
Before the upgrade, everythings worked fine.

I tried to launch manually the shell command with user root/centreon/centreon_engine and email is well sending

I searched in all logs in /var/log and I don't find any error.

I also tried to remplace directly @MAILER@ by /usr/bin/mail /bin/mail and no effect.

Thanks for your support

**Comment by Mickael06** [comment]
Same thing on a fresh install and restore of my centreon backup.

**Comment by sbraz** [comment]
Hi @Mickael06,
I had a similar problem on a fresh install and I noticed that `mailx` (which provides `/bin/mail`) was not installed.
Did you check that this binary exists on your system? I'm not sure this will help since the command worked when you ran it yourself but I thought it was worth mentioning.
