### ISSUE TITLE
Downtimes and Event Log not reflecting DST(Summer/Winter time) correctly

### ISSUE THREAD

**Issue by ja-frog** [centreon/centreon#9632]
Since the recent change to summer time, I have noticed the following behavior. Please note that we have been using Centreon for many years and have not had this issue previously. I could not say with any certainty what version we would have been on at the last time change, though I believe that it would have been the 20.04 line.

Events in the Event Logs are showing a timestamp of one hour earlier than they actually occurred.
Downtime:
		If set from the Downtimes screen, the default start time is in the past 1 hour.
		If set from the Downtimes screen, the actual start/end time of the downtime is one hour earlier than what is specified.                           
                     For example, if I set the downtime to start at 10am, then then downtime will be created starting at 9am.

Many other elements related to time are correct, including:
	The clock in upper right
	Timeline, if I click on an individual service in the Resource Status view
	Last state change, if I click on an individual service in the Resource Status view
	Graphs
	Downtimes, if set from the Resource Status view

Our timezone: America/Chicago. Currently -5 from GMT.

Browsers:
	Firefox 87
	Chrome 89

OS: CentOS Linux release 7.9.2009 (Core)

Running on VMWare ESXi 7

Packages:
centreon-20.10.4-6.el7.centos.noarch
centreon-auto-discovery-server-20.10.3-2.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.4-6.el7.centos.noarch
centreon-broker-20.10.3-5.el7.centos.x86_64
centreon-broker-cbd-20.10.3-5.el7.centos.x86_64
centreon-broker-cbmod-20.10.3-5.el7.centos.x86_64
centreon-broker-core-20.10.3-5.el7.centos.x86_64
centreon-broker-storage-20.10.3-5.el7.centos.x86_64
centreon-clib-20.10.0-2.el7.centos.x86_64
centreon-common-20.10.4-6.el7.centos.noarch
centreon-connector-20.10.0-2.el7.centos.x86_64
centreon-connector-perl-20.10.0-2.el7.centos.x86_64
centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
centreon-cwrapper-perl-0.1-1.el7.centos.x86_64
centreon-database-20.10.4-6.el7.centos.noarch
centreon-engine-20.10.2-2.el7.centos.x86_64
centreon-engine-daemon-20.10.2-2.el7.centos.x86_64
centreon-engine-extcommands-20.10.2-2.el7.centos.x86_64
centreon-gorgone-20.10.3-1.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.3-1.el7.centos.noarch
centreon-license-manager-20.10.2-1.el7.centos.noarch
centreon-license-manager-common-20.10.2-1.el7.centos.noarch
centreon-perl-libs-20.10.4-6.el7.centos.noarch
centreon-poller-centreon-engine-20.10.4-6.el7.centos.noarch
centreon-pp-manager-20.10.1-3.el7.centos.noarch
centreon-release-20.10-2.el7.centos.noarch
centreon-trap-20.10.4-6.el7.centos.noarch
centreon-web-20.10.4-6.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch

PHP Error Logs: None generated

/var/log/centreon-gorgone/gorgoned.log
2021-03-30 09:07:51 - INFO - [legacycmd] Handling command 'EXTERNALCMD', Target: '1', Parameters: '[1617113270] SCHEDULE_SVC_DOWNTIME;mcgpop-3;Blade_Uptime;1617109620;1617113220;1;0;3600;jmcdermid;Test'
2021-03-30 09:07:51 - INFO - [engine] Processing external command '[1617113270] SCHEDULE_SVC_DOWNTIME;mcgpop-3;Blade_Uptime;1617109620;1617113220;1;0;3600;jmcdermid;Test'

/var/log/centreon/centcore.log: None generated

**Comment by grosbedos** [comment]
Hi,

Same here with 19.04. We use 19.04 for two years now, and it's the first time it append.
Event log are showing a timestamp of one hour earlier than they actually occurred.

All server have the correct time..

**Comment by dgarandel** [comment]
Same issue since last summer time changed. Issue on v19.10 and v20.10.1. On old test server v2.8 no issue.
on production 19.10 & 20.10 we have php7.2 and date.timezone are correctly configured since 2 years
Pb appear on all page with show date/time and also on graphs. All data's on databases are correct,also on RRD files

**Comment by joschi99** [comment]
Same issue, also after a reboot problem still there on 20.04.x and 20.10.x

**Comment by joschi99** [comment]
Also after update to 20.10.5 problem is still there

**Comment by AlexB-LP** [comment]
Hi,

We encounter the same issue, on a 19.10 plateform. We are using "Europe/Paris" timezone, and having a 1 hour late delay on time display since DST.

Looking more closely, this date/time translation is made by [dateMoment.js](www/include/common/javascript/centreon/dateMoment.js)

In our case, deleting timezone translation ( .tz(userTimezone) ) seems resolving this issue. This need to be test on other Timezone. I guess it's ok because our Central server is using the same TZ as our user.

But I don't know if purely deleting this piece of code will do, juggling with timezone is always a nightmare for me !

If people with more skill with timezone want to look at it, it'll be great.

**Comment by AlexB-LP** [comment]
It look like the javascript moment-timezone-with-data-min.js is outdated, and don't have timezone shift after Fall 2020.
Updating this script should solved this issue.

Looking at this file, I noticed a PR made 9 days ago : #9623

**Comment by viaDomitia** [comment]
Hi !
Centreon 19.4.0 here. Same problem.
Try updating the script moment-timezone-with-data-min.js as describe in PR #9623 but unfortunately the issue is still there.

**Comment by AlexB-LP** [comment]
Hi @viaDomitia 

We updated our plateform to 19.10.22 this morning, and I can confirm the issue is solved.

Be careful when testing, your Central Web should be restarted (httpd et php), and your navigator cache deleted (because javascript is often stocked in it). Also, be aware about network cache if any in your organization.

**Comment by ja-frog** [comment]
I updated to version 20.10.5 and then applied the fix in PR #9623. After clearing my cache the issue was resolved.
